create extension if not exists pgcrypto;
create schema if not exists almacen;
create schema if not exists dealer;
create schema if not exists public;
create schema if not exists tran;
;

create table if not exists almacen.AlmacenTablaAmortizaciones(
	"IdTablaAmortizacion" integer NOT NULL,
	"IdPrestamo" integer NOT NULL,
	"OrdenPago" integer NOT NULL,
	"Vencimiento" timestamptz NOT NULL,
	"PagoCierre" numeric(18,2) NOT NULL,
	"PagoSeguro" numeric(18,2) NOT NULL,
	"PagoCapital" numeric(18,2) NOT NULL,
	"PagoInteres" numeric(18,2) NOT NULL,
	"DescuentoInteres" numeric(18,2) NOT NULL,
	"DescuentoCierre" numeric(18,2) NOT NULL,
	"DescuentoSeguro" numeric(18,2) NOT NULL,
	"DescuentoCapital" numeric(18,2) NOT NULL,
	"PagoFecha" timestamptz NULL,
	"FechaFinMora" timestamptz NULL,
	"EstaPago" boolean NOT NULL,
	"DetenerMora" boolean NOT NULL,
	"SanAcumulado" numeric(18,2) NOT NULL,
	"Nota" text NULL,
	"Descuento" numeric(18,2) NULL,
	"Reversar" boolean NOT NULL,
	"InteresMora" numeric(9,6) NOT NULL,
	"DiasGraciaMora" integer NOT NULL,
	"DescuentoMora" numeric(18,2) NOT NULL,
	"Mora" numeric(18,2) NOT NULL
)
;
;

create table if not exists almacen.Amortizaciones(
	"IdAmortizacion" integer NOT NULL,
	"IdPrestamo" integer NOT NULL,
	"OrdenPago" integer NOT NULL,
	"Vencimiento" timestamptz NOT NULL,
	"GastoCierre" numeric(18,2) NOT NULL,
	"Seguro" numeric(18,2) NOT NULL,
	"Interes" numeric(18,2) NOT NULL,
	"InteresMora" numeric(18,6) NOT NULL,
	"Capital" numeric(18,2) NOT NULL,
	"GastoCierreAcumulado" numeric(18,2) NOT NULL,
	"SeguroAcumulado" numeric(18,2) NOT NULL,
	"InteresAcumulado" numeric(18,2) NOT NULL,
	"CapitalAcumulado" numeric(18,2) NOT NULL,
	"MoraAcumulado" numeric(18,2) NOT NULL,
	"DiasGraciaMora" integer NOT NULL,
	"DetenerMora" boolean NOT NULL,
	"Frecuencia" integer NOT NULL,
	"FechaFinMora" timestamptz NULL,
	"PagoFecha" timestamptz NULL,
	"Mora" numeric(18,2) NOT NULL,
	"RegID" uuid default gen_random_uuid() NOT NULL,
	"Gps" numeric(18,2) NOT NULL,
	"GpsAcumulado" numeric(18,2) NOT NULL,
 constraint "PK_AlmacenAmortizaciones" primary key 
(
	"IdAmortizacion" ASC
)
)
;
;

create table if not exists public.Alertas(
	"IdAlerta" integer generated by default as identity NOT NULL,
	"IdUsuario" integer NOT NULL,
	"Fecha" timestamptz NOT NULL,
	"Descripcion" text NOT NULL,
	"Restringir" boolean NOT NULL,
	"RegID" uuid default gen_random_uuid() NOT NULL,
 constraint "PK_Alertas" primary key 
(
	"IdAlerta" ASC
)
)
;
;

create table if not exists public.AlertasDetalles(
	"IdAlertaDetalle" integer generated by default as identity NOT NULL,
	"IdAlerta" integer NOT NULL,
	"IdRestriccion" integer NOT NULL,
	"Valor" varchar(64) NOT NULL,
	"RegID" uuid default gen_random_uuid() NOT NULL,
 constraint "PK_AlertasDetalles" primary key 
(
	"IdAlertaDetalle" ASC
)
)
;
;

create table if not exists public.aspnet_Applications(
	"ApplicationName" varchar(256) NOT NULL,
	"LoweredApplicationName" varchar(256) NOT NULL,
	"ApplicationId" uuid NOT NULL,
	"Description" varchar(256) NULL,
primary key 
(
	"ApplicationId" ASC
),
unique 
(
	"LoweredApplicationName" ASC
),
unique 
(
	"ApplicationName" ASC
)
)
;
;

create table if not exists public.aspnet_Membership(
	"ApplicationId" uuid NOT NULL,
	"UserId" uuid NOT NULL,
	"Password" varchar(128) NOT NULL,
	"PasswordFormat" integer NOT NULL,
	"PasswordSalt" varchar(128) NOT NULL,
	"MobilePIN" varchar(16) NULL,
	"Email" varchar(256) NULL,
	"LoweredEmail" varchar(256) NULL,
	"PasswordQuestion" varchar(256) NULL,
	"PasswordAnswer" varchar(128) NULL,
	"IsApproved" boolean NOT NULL,
	"IsLockedOut" boolean NOT NULL,
	"CreateDate" timestamptz NOT NULL,
	"LastLoginDate" timestamptz NOT NULL,
	"LastPasswordChangedDate" timestamptz NOT NULL,
	"LastLockoutDate" timestamptz NOT NULL,
	"FailedPasswordAttemptCount" integer NOT NULL,
	"FailedPasswordAttemptWindowStart" timestamptz NOT NULL,
	"FailedPasswordAnswerAttemptCount" integer NOT NULL,
	"FailedPasswordAnswerAttemptWindowStart" timestamptz NOT NULL,
	"Comment" text NULL,
primary key 
(
	"UserId" ASC
)
)
;
;

create table if not exists public.aspnet_Paths(
	"ApplicationId" uuid NOT NULL,
	"PathId" uuid NOT NULL,
	"Path" varchar(256) NOT NULL,
	"LoweredPath" varchar(256) NOT NULL,
primary key 
(
	"PathId" ASC
)
)
;
;

create table if not exists public.aspnet_PersonalizationAllUsers(
	"PathId" uuid NOT NULL,
	"PageSettings" bytea NOT NULL,
	"LastUpdatedDate" timestamptz NOT NULL,
primary key 
(
	"PathId" ASC
)
)
;
;

create table if not exists public.aspnet_PersonalizationPerUser(
	"Id" uuid NOT NULL,
	"PathId" uuid NULL,
	"UserId" uuid NULL,
	"PageSettings" bytea NOT NULL,
	"LastUpdatedDate" timestamptz NOT NULL,
primary key 
(
	"Id" ASC
)
)
;
;

create table if not exists public.aspnet_Profile(
	"UserId" uuid NOT NULL,
	"PropertyNames" text NOT NULL,
	"PropertyValuesString" text NOT NULL,
	"PropertyValuesBinary" bytea NOT NULL,
	"LastUpdatedDate" timestamptz NOT NULL,
primary key 
(
	"UserId" ASC
)
)
;
;

create table if not exists public.aspnet_Roles(
	"ApplicationId" uuid NOT NULL,
	"RoleId" uuid NOT NULL,
	"RoleName" varchar(256) NOT NULL,
	"LoweredRoleName" varchar(256) NOT NULL,
	"Description" varchar(256) NULL,
primary key 
(
	"RoleId" ASC
)
)
;
;

create table if not exists public.aspnet_SchemaVersions(
	"Feature" varchar(128) NOT NULL,
	"CompatibleSchemaVersion" varchar(128) NOT NULL,
	"IsCurrentVersion" boolean NOT NULL,
primary key 
(
	"Feature" ASC,
	"CompatibleSchemaVersion" ASC
)
)
;
;

create table if not exists public.aspnet_Users(
	"ApplicationId" uuid NOT NULL,
	"UserId" uuid NOT NULL,
	"UserName" varchar(256) NOT NULL,
	"LoweredUserName" varchar(256) NOT NULL,
	"MobileAlias" varchar(16) NULL,
	"IsAnonymous" boolean NOT NULL,
	"LastActivityDate" timestamptz NOT NULL,
primary key 
(
	"UserId" ASC
)
)
;
;

create table if not exists public.aspnet_UsersInRoles(
	"UserId" uuid NOT NULL,
	"RoleId" uuid NOT NULL,
primary key 
(
	"UserId" ASC,
	"RoleId" ASC
)
)
;
;

create table if not exists public.aspnet_WebEvent_Events(
	"EventId" char(32) NOT NULL,
	"EventTimeUtc" timestamptz NOT NULL,
	"EventTime" timestamptz NOT NULL,
	"EventType" varchar(256) NOT NULL,
	"EventSequence" numeric(19,0) NOT NULL,
	"EventOccurrence" numeric(19,0) NOT NULL,
	"EventCode" integer NOT NULL,
	"EventDetailCode" integer NOT NULL,
	"Message" varchar(1024) NULL,
	"ApplicationPath" varchar(256) NULL,
	"ApplicationVirtualPath" varchar(256) NULL,
	"MachineName" varchar(256) NOT NULL,
	"RequestUrl" varchar(1024) NULL,
	"ExceptionType" varchar(256) NULL,
	"Details" text NULL,
primary key 
(
	"EventId" ASC
)
)
;
;

create table if not exists public.Auditorias(
	"IDAuditoria" integer generated by default as identity NOT NULL,
	"Logs" text NOT NULL,
	"Fecha" timestamptz NOT NULL,
	"UsuarioApp" varchar(64) NOT NULL,
	"UsuarioDom" varchar(64) NOT NULL,
	"TerminalDom" varchar(64) NOT NULL,
	"IP" varchar(64) NOT NULL,
	"Transaccion" uuid NOT NULL,
 constraint "PK_Auditorias" primary key 
(
	"IDAuditoria" ASC
)
)
;
;

create table if not exists public.Bancos(
	"IdBanco" integer generated by default as identity NOT NULL,
	"Nombre" varchar(50) NOT NULL,
	"isNotLock" boolean NOT NULL,
	"imgUrl" text NOT NULL,
	"RegID" uuid default gen_random_uuid() NOT NULL,
 constraint "PK_Bancos" primary key 
(
	"IdBanco" ASC
)
)
;
;

create table if not exists public.Carteras(
	"IdCartera" integer generated by default as identity NOT NULL,
	"IdEmpresa" integer NOT NULL,
	"FechaCreacion" timestamptz default now() NOT NULL,
	"RazonSocial" varchar(64) NOT NULL,
	"NombreComercial" varchar(64) NOT NULL,
	"NombreParaMostrar" varchar(64) NULL,
	"RNC" varchar(20) NOT NULL,
	"Direccion" varchar(128) NOT NULL,
	"Telefono" varchar(256) NULL,
	"Presidente" varchar(64) NOT NULL,
	"CedulaPresidente" varchar(32) NOT NULL,
	"Abogado" varchar(64) NOT NULL,
	"EstadoCivilAbogado" integer NOT NULL,
	"CedulaAbogado" varchar(32) NOT NULL,
	"DireccionAbogado" varchar(128) NOT NULL,
	"Alguacil" varchar(64) NOT NULL,
	"Tasa" numeric(8,4) NOT NULL,
	"Mora" numeric(8,4) NOT NULL,
	"Cuotas" integer NOT NULL,
	"GastoCierre" numeric(8,2) NOT NULL,
	"UrlLogo" varchar(50) NOT NULL,
	"ContadorCuentas" integer NOT NULL,
	"ContadorPrestamos" integer NOT NULL,
	"ContadorRecibos" integer NOT NULL,
	"SufijoCartera" varchar(20) NOT NULL,
	"Banco" varchar(64) NOT NULL,
	"NoCuenta" varchar(20) NOT NULL,
	"IdTipoRecibo" integer NOT NULL,
	"AutorizacionNombre" varchar(64) NULL,
	"AutorizacionDireccion" varchar(64) NULL,
	"AutorizacionIdentificacion" varchar(64) NULL,
	"ProcesoLegalAutomatico" boolean NOT NULL,
	"CostoBasicoLegal" numeric(18,2) NOT NULL,
	"InicioProcesoLegalCuotasVencidas" integer NOT NULL,
	"InicioProcesoLegalDias" integer NOT NULL,
	"Testigo1" varchar(64) NOT NULL,
	"Testigo2" varchar(64) NOT NULL,
	"CedulaTestigo1" varchar(13) NULL,
	"CedulaTestigo2" varchar(13) NULL,
	"RegID" uuid default gen_random_uuid() NOT NULL,
	"PorcientoPagoMinimo" numeric(6,2) NOT NULL,
	"Penalidad" numeric(5,4) NOT NULL,
	"MaxAbonoSobreCapital" numeric(5,4) NOT NULL,
	"MinAbonoSobreCapital" numeric(5,4) NOT NULL,
	"Activo" boolean NOT NULL,
 constraint "PK_Carteras" primary key 
(
	"IdCartera" ASC
)
)
;
;

create table if not exists public.Categorias(
	"IdCategoria" integer generated by default as identity NOT NULL,
	"Nombre" varchar(64) NOT NULL,
	"RegID" uuid default gen_random_uuid() NOT NULL,
 constraint "PK_Categorias" primary key 
(
	"IdCategoria" ASC
)
)
;
;

create table if not exists public.Cotizaciones(
	"IdCotizacion" integer generated by default as identity NOT NULL,
	"IdUsuario" integer NOT NULL,
	"Fecha" timestamptz NOT NULL,
	"Capital" numeric(18,2) NOT NULL,
	"Interes" numeric(6,4) NOT NULL,
	"Cuotas" integer NOT NULL,
	"GastoCierre" numeric(18,2) NOT NULL,
	"FrecuenciaPago" integer NOT NULL,
	"IdTipoPrestamo" integer NOT NULL,
	"DescripcionGarantia" text NOT NULL,
	"RegID" uuid default gen_random_uuid() NOT NULL,
 constraint "PK_Cotizaciones" primary key 
(
	"IdCotizacion" ASC
)
)
;
;

create table if not exists public.Cuentas(
	"IdCuenta" integer generated by default as identity NOT NULL,
	"IdCartera" integer NOT NULL,
	"Codigo" text generated always as ("Prefijo"||CONVERT(text,"CuentaNo",(0))) stored,
	"Prefijo" varchar(16) NOT NULL,
	"CuentaNo" integer NOT NULL,
	"EstaEnListaNegra" boolean NOT NULL,
	"UsuarioId" integer NOT NULL,
	"Nombres" varchar(128) NOT NULL,
	"Apellidos" varchar(128) NOT NULL,
	"Apodo" varchar(64) NULL,
	"Identificacion" varchar(32) NOT NULL,
	"FechaNacimiento" timestamptz NOT NULL,
	"Sexo" char(1) NOT NULL,
	"Correo" varchar(128) NULL,
	"EstadoCivil" char(1) NOT NULL,
	"NombreConyugue" varchar(128) NULL,
	"IdentificacionConyugue" varchar(32) NULL,
	"Empresa" varchar(50) NULL,
	"DireccionEmpresa" varchar(256) NULL,
	"Cargo" varchar(50) NULL,
	"NombreJefe" varchar(50) NULL,
	"CantidadHijos" integer NOT NULL,
	"AceptarCheque" boolean NOT NULL,
	"Bloqueado" boolean NOT NULL,
	"BloquearCobro" boolean NOT NULL,
	"Descontar" boolean NOT NULL,
	"Nacionalidad" varchar(128) NOT NULL,
	"Ingresos" numeric(18,2) NOT NULL,
	"TipoDocumento" integer NOT NULL,
	"Profesion" varchar(50) NULL,
	"Ocupacion" integer NOT NULL,
	"TipoRecidencia" integer NOT NULL,
	"LugarTrabajoConyugue" varchar(50) NULL,
	"DireccionLugarTrabajoConyugue" varchar(128) NULL,
	"TelefonoTrabajoConyugue" varchar(20) NULL,
	"CelularConyugue" varchar(20) NULL,
	"RegID" uuid default gen_random_uuid() NOT NULL,
 constraint "PK_Cuentas" primary key 
(
	"IdCuenta" ASC
)
)
;
;

create table if not exists public.Depositos(
	"IdDeposito" integer generated by default as identity NOT NULL,
	"IdCartera" integer NOT NULL,
	"Fecha" timestamptz NOT NULL,
	"IdUsuario" integer NOT NULL,
	"TipoDeposito" integer NOT NULL,
	"Depositante" varchar(128) NOT NULL,
	"MontoEfectivo" numeric(18,2) NOT NULL,
	"DescripcionEfectivo" xml NOT NULL,
	"MontoCheques" numeric(18,2) NOT NULL,
	"MontoTransferencia" numeric(18,2) NOT NULL,
	"CantidadTransferencia" integer NOT NULL,
	"CantidadCheques" integer NOT NULL,
	"Banco" varchar(64) NOT NULL,
	"NoCuenta" varchar(20) NOT NULL,
	"Contabilizado" boolean NOT NULL,
	"ReferenciaContable" integer NULL,
	"RegID" uuid default gen_random_uuid() NOT NULL,
 constraint "PK_Depositos" primary key 
(
	"IdDeposito" ASC
)
)
;
;

create table if not exists public.DesembolsoDetalles(
	"IdDesembolsoDetalle" integer generated by default as identity NOT NULL,
	"IdPrestamo" integer NOT NULL,
	"Nombre" varchar(128) NOT NULL,
	"Concepto" text NOT NULL,
	"Monto" numeric(18,2) NOT NULL,
	"Nota" text NULL,
	"RegID" uuid default gen_random_uuid() NOT NULL,
 constraint "PK_DetallesDesembolsos" primary key 
(
	"IdDesembolsoDetalle" ASC
)
)
;
;

create table if not exists public.DocumentosFisicos(
	"IdDocumentoFisico" integer generated by default as identity NOT NULL,
	"Nombre" varchar(128) NOT NULL,
	"Ubicacion" varchar(256) NOT NULL,
	"ContentType" varchar(16) NOT NULL,
	"Etiqueta" integer NOT NULL,
	"descripcion" text generated always as ('Valores que representan una descripción de la imagen 0: otros, 1: Automovil Frente, 2: 
Automovil Tracero, 3:Automovil Lado, 4:Cliente Rostro, 5:Documento Saldo, 6: Documento Identificación, 
7:Documento Notificación, 8:Documento Sentencia, 9:Inmueble, 10:Terreno'),
	"RegID" uuid default gen_random_uuid() NOT NULL,
 constraint "PK_DocumentosFisicos" primary key 
(
	"IdDocumentoFisico" ASC
)
)
;
;

create table if not exists public.DocumentosFisicosEnGaratia(
	"IdGarantia" integer NOT NULL,
	"IdDocumentoFisico" integer NOT NULL,
 constraint "PK_DocumentosFisicosEnGaratia" primary key 
(
	"IdGarantia" ASC,
	"IdDocumentoFisico" ASC
)
)
;
;

create table if not exists public.DocumentosFisicosEnListaNegra(
	"IdListaNegra" integer NOT NULL,
	"IdDocumentoFisico" integer NOT NULL,
 constraint "PK_DocumentosFisicosEnListaNegra" primary key 
(
	"IdListaNegra" ASC,
	"IdDocumentoFisico" ASC
)
)
;
;

create table if not exists public.DocumentosFisicosEnPrestamo(
	"IdPrestamo" integer NOT NULL,
	"IdDocumentoFisico" integer NOT NULL,
 constraint "PK_DocumentosFisicosEnPrestamo" primary key 
(
	"IdPrestamo" ASC,
	"IdDocumentoFisico" ASC
)
)
;
;

create table if not exists public.ELMAH_Error(
	"ErrorId" uuid NOT NULL,
	"Application" varchar(60) NOT NULL,
	"Host" varchar(50) NOT NULL,
	"Type" varchar(100) NOT NULL,
	"Source" varchar(60) NOT NULL,
	"Message" varchar(500) NOT NULL,
	"User" varchar(50) NOT NULL,
	"StatusCode" integer NOT NULL,
	"TimeUtc" timestamptz NOT NULL,
	"Sequence" integer generated by default as identity NOT NULL,
	"AllXml" text NOT NULL,
 constraint "PK_ELMAH_Error" primary key 
(
	"ErrorId" ASC
)
)
;
;

create table if not exists public.Empresas(
	"IdEmpresa" integer generated by default as identity NOT NULL,
	"FechaCreacion" timestamptz default now() NOT NULL,
	"RazonSocial" varchar(64) NOT NULL,
	"NombreComercial" varchar(64) NOT NULL,
	"RNC" varchar(20) NOT NULL,
	"Direccion" varchar(128) NOT NULL,
	"Telefono" varchar(256) NULL,
	"Presidente" varchar(64) NOT NULL,
	"CedulaPresidente" varchar(32) NOT NULL,
	"Abogado" varchar(64) NOT NULL,
	"EstadoCivilAbogado" integer NOT NULL,
	"CedulaAbogado" varchar(32) NOT NULL,
	"DireccionAbogado" varchar(128) NOT NULL,
	"Alguacil" varchar(64) NOT NULL,
	"Tasa" numeric(8,4) NOT NULL,
	"Mora" numeric(8,4) NOT NULL,
	"Cuotas" integer NOT NULL,
	"GastoCierre" numeric(8,4) NOT NULL,
	"UrlLogo" varchar(128) NOT NULL,
	"Banco" varchar(64) NOT NULL,
	"NoCuenta" varchar(20) NOT NULL,
	"EmailFrom" varchar(64) NULL,
	"EmailTo" varchar(64) NULL,
	"EmailAccount" varchar(64) NULL,
	"EmailSMTP" varchar(64) NULL,
	"EmailPort" integer NULL,
	"EmailSSL" boolean NULL,
	"EmailActivo" boolean NULL,
	"EmailAccountPassword" varchar(64) NULL,
	"NotificacionSaldoActivado" boolean NULL,
	"EmailParaNotificarSaldo" varchar(64) NULL,
	"NotificacionCobrosActivado" boolean NULL,
	"EmailNotificacionCobros" varchar(64) NULL,
	"EmpresaEnContabilidadID" integer NULL,
	"RegID" uuid default gen_random_uuid() NOT NULL,
	"Activo" boolean NOT NULL,
	"Penalidad" numeric(5,4) NOT NULL,
	"MaxAbonoSobreCapital" numeric(5,4) NOT NULL,
	"MinAbonoSobreCapital" numeric(5,4) NOT NULL,
	"ApiKey" uuid default gen_random_uuid() NOT NULL,
	"AutoAsignarNcf" boolean NOT NULL,
	"EcfApikey" varchar(128) NULL,
	"EmailEmpresa" varchar(64) NULL,
	"CertificacionDgii" boolean NOT NULL,
	"FechaCertificacion" timestamptz NULL,
 constraint "PK_Secuencias" primary key 
(
	"IdEmpresa" ASC
)
)
;
;

create table if not exists public.EmpresasDeServicios(
	"IdEmpresaDeServicio" integer generated by default as identity NOT NULL,
	"Nombre" varchar(32) NOT NULL,
	"TipoEmpresaDeServicio" integer NOT NULL,
	"IdMunicipio" integer NOT NULL,
	"Sector" varchar(48) NULL,
	"Calle" varchar(48) NULL,
	"Contacto" varchar(32) NULL,
	"RNC" varchar(11) NOT NULL,
	"Telefono1" varchar(20) NOT NULL,
	"Telefono2" varchar(20) NULL,
	"RegID" uuid default gen_random_uuid() NOT NULL,
 constraint "PK_EmpresasDeServicios" primary key 
(
	"IdEmpresaDeServicio" ASC
)
)
;
;

create table if not exists public.EmpresaServiciosEnEmpresas(
	"IdEmpresa" integer NOT NULL,
	"IdEmpresaDeServicio" integer NOT NULL,
 constraint "PK_EmpresaServiciosEnEmpresas" primary key 
(
	"IdEmpresa" ASC,
	"IdEmpresaDeServicio" ASC
)
)
;
;

create table if not exists public.Estados(
	"IdEstado" integer NOT NULL,
	"Nombre" varchar(50) NOT NULL,
 constraint "PK_Estados" primary key 
(
	"IdEstado" ASC
)
)
;
;

create table if not exists public.Garantias(
	"IdGarantia" integer generated by default as identity NOT NULL,
	"IdPrestamo" integer NOT NULL,
	"GarantiaTipo" integer NOT NULL,
	"Placa" varchar(32) NULL,
	"Matricula" varchar(32) NULL,
	"FechaMatricula" timestamptz NULL,
	"IdModelo" integer NOT NULL,
	"Pasajeros" integer NULL,
	"Color" varchar(50) NULL,
	"FabricacionFecha" integer NULL,
	"NumeroMotor" varchar(32) NULL,
	"NumeroChasis" varchar(64) NULL,
	"PlacaAnterior" varchar(32) NULL,
	"IdAseguradora" integer NOT NULL,
	"NumeroPoliza" varchar(64) NULL,
	"CreacionSeguro" timestamptz NULL,
	"VencimientoSeguro" timestamptz NULL,
	"SeguroEndozadoA" varchar(128) NULL,
	"NumeroLocalizadorSeguridad" varchar(64) NULL,
	"VencimientoLocalizador" timestamptz NULL,
	"Descripcion" text NULL,
	"GPS" varchar(50) NULL,
	"NombreAseguradora" varchar(64) NULL,
	"NombreModelo" varchar(64) NULL,
	"NombreMarca" varchar(64) NULL,
	"Tipo" varchar(64) NULL,
	"Estilo" varchar(64) NULL,
	"FotoFrente" varchar(256) NULL,
	"FotoTrasero" varchar(256) NULL,
	"FotoDerecha" varchar(256) NULL,
	"FotoIzquierda" varchar(256) NULL,
	"IdVehiculoEstilo" integer NOT NULL,
	"IdVehiculoTipo" integer NOT NULL,
	"ValorGarantia" numeric(18,2) NOT NULL,
	"IdGPS" integer NOT NULL,
	"RegID" uuid default gen_random_uuid() NOT NULL,
	"DescripcionResumida"  AS (case when "GarantiaTipo"=(1) then ((("NombreMarca"||' ')||"NombreModelo")||' ')||CONVERT("varchar","FabricacionFecha") else "Descripcion" end) stored,
	"DescripcionDetallada" text generated always as (case when "GarantiaTipo"=(1) then (((((((((((('Tipo:'||"Tipo")||', Marca ')||"NombreMarca")||', Modelo ')||"NombreModelo")||', año ')||CONVERT("varchar","FabricacionFecha"))||', Color ')||"Color")||', Placa ')||"Placa")||', Chasis ')||"NumeroChasis" else "Descripcion" end) stored,
 constraint "PK_Garantias" primary key 
(
	"IdGarantia" ASC
)
)
;
;

create table if not exists public.Grupos(
	"IDGrupo" integer generated by default as identity NOT NULL,
	"NombreGrupo" varchar(64) NOT NULL,
	"RegID" uuid default gen_random_uuid() NOT NULL,
 constraint "PK_Grupos" primary key 
(
	"IDGrupo" ASC
)
)
;
;

create table if not exists public.GruposRoles(
	"IDGrupoRol" integer generated by default as identity NOT NULL,
	"IDGrupo" integer NOT NULL,
	"NombreRol" varchar(64) NOT NULL,
	"RegID" uuid default gen_random_uuid() NOT NULL,
 constraint "PK_GruposRoles" primary key 
(
	"IDGrupoRol" ASC
)
)
;
;

create table if not exists public.ListasNegras(
	"IdListaNegra" integer generated by default as identity NOT NULL,
	"IdUsuario" integer NOT NULL,
	"Fecha" timestamptz NOT NULL,
	"Descripcion" text NOT NULL,
	"RegID" uuid default gen_random_uuid() NOT NULL,
 constraint "PK_ListasNegras" primary key 
(
	"IdListaNegra" ASC
)
)
;
;

create table if not exists public.LLaves(
	"IDLLave" integer generated by default as identity NOT NULL,
	"UserNameUsuario" varchar(50) NULL,
	"NombreUsuario" varchar(50) NULL,
	"UserNameSupervisor" varchar(50) NOT NULL,
	"Accion" integer NOT NULL,
	"FechaCreacion" timestamptz default now() NOT NULL,
	"FechaExpiracion" timestamptz NOT NULL,
	"Activo" boolean NOT NULL,
	"IDReg" uuid NULL,
	"Referencia" varchar(18) NULL,
	"ValorDecimal" numeric(18,2) NULL,
 constraint "PK_LLaves" primary key 
(
	"IDLLave" ASC
)
)
;
;

create table if not exists public.Localizaciones(
	"IdLocalizacion" integer generated by default as identity NOT NULL,
	"IdCuenta" integer NOT NULL,
	"IdMunicipio" integer NOT NULL,
	"Sector" varchar(128) NULL,
	"SubSector" varchar(128) NULL,
	"Calle" varchar(64) NULL,
	"ReferenciaLocalidad" text NULL,
	"Latitud" double precision NULL,
	"Longitud" double precision NULL,
	"DireccionCompleta" text generated always as (((((('calle '||"calle")||' sector ')||"Sector")||', ')||"SubSector")||'.'),
	"RegID" uuid default gen_random_uuid() NOT NULL,
 constraint "PK_Localizaciones" primary key 
(
	"IdLocalizacion" ASC
)
)
;
;

create table if not exists public.Marcas(
	"IdMarca" integer generated by default as identity NOT NULL,
	"Nombre" varchar(128) NOT NULL,
	"RegID" uuid default gen_random_uuid() NOT NULL,
 constraint "PK_Marcas" primary key 
(
	"IdMarca" ASC
)
)
;
;

create table if not exists public.Modelos(
	"IdModelo" integer generated by default as identity NOT NULL,
	"Nombre" varchar(128) NOT NULL,
	"IdMarca" integer NOT NULL,
	"RegID" uuid default gen_random_uuid() NOT NULL,
 constraint "PK_Modelos" primary key 
(
	"IdModelo" ASC
)
)
;
;

create table if not exists public.Municipios(
	"IdMunicipio" integer generated by default as identity NOT NULL,
	"Nombre" varchar(80) NOT NULL,
	"IdProvincia" integer NOT NULL,
	"RegID" uuid default gen_random_uuid() NOT NULL,
 constraint "PK_Municipio" primary key 
(
	"IdMunicipio" ASC
)
)
;
;

create table if not exists public.NCFAsignaciones(
	"IdDetalleNcf" bigint NOT NULL,
	"IdMovimiento" integer NOT NULL,
 constraint "PK_NCFAsignaciones" primary key 
(
	"IdDetalleNcf" ASC,
	"IdMovimiento" ASC
)
)
;
;

create table if not exists public.NCFDetalles(
	"IdDetalleNcf" bigint generated by default as identity NOT NULL,
	"IdRangoNcf" bigint NOT NULL,
	"RNC" varchar(20) NOT NULL,
	"Secuencia" bigint NOT NULL,
	"NCF" varchar(24) NOT NULL,
	"Disponible" boolean NOT NULL,
	"Activo" boolean NOT NULL,
	"FechaAsignacion" timestamptz NULL,
	"Monto" numeric(18,2) NULL,
	"Fecha" timestamptz NOT NULL,
	"RegID" uuid default gen_random_uuid() NOT NULL,
	"EstadoDgii" integer NULL,
	"QrCode" text NULL,
	"AlertasDgii" text NULL,
	"SecuenciaUtilizadaDgii" boolean NULL,
	"Errores" text NULL,
	"NCFModificado" varchar(24) NULL,
	"CodigoSeguridad" varchar(8) NULL,
	"FechaFirma" varchar(20) NULL,
 constraint "PK_NCFDetalles" primary key 
(
	"IdDetalleNcf" ASC
),
 constraint "IX_NCFDetalles" unique 
(
	"NCF" ASC,
	"RNC" ASC
)
)
;
;

create table if not exists public.NCFRangos(
	"IdRangoNcf" bigint generated by default as identity NOT NULL,
	"IdEmpresa" integer NOT NULL,
	"Tipo" integer NOT NULL,
	"Inicio" bigint NOT NULL,
	"Fin" bigint NOT NULL,
	"Vencimiento" timestamptz NULL,
	"FechaCreacion" timestamptz default now() NOT NULL,
	"FechaModificacion" timestamptz NULL,
	"UsuarioCreacion" varchar(128) NOT NULL,
	"UsuarioModificacion" varchar(128) NULL,
	"RegID" uuid default gen_random_uuid() NOT NULL,
 constraint "PK_NCFRangos" primary key 
(
	"IdRangoNcf" ASC
)
)
;
;

create table if not exists public.NotasListasNegras(
	"IdNotaListaNegra" integer generated by default as identity NOT NULL,
	"IdListaNegra" integer NOT NULL,
	"IdUsuario" integer NOT NULL,
	"Fecha" timestamptz NOT NULL,
	"TipoDescripcion" integer NOT NULL,
	"Descripcion" text NOT NULL,
	"RegID" uuid default gen_random_uuid() NOT NULL,
 constraint "PK_NotasListasNegras" primary key 
(
	"IdNotaListaNegra" ASC
)
)
;
;

create table if not exists public.Ofertas(
	"IdOferta" integer generated by default as identity NOT NULL,
	"Monto" numeric(18,2) NOT NULL,
	"Fecha" timestamptz NOT NULL,
	"IdProveedor" integer NOT NULL,
	"Garantia" varchar(256) NOT NULL,
	"RegID" uuid default gen_random_uuid() NOT NULL,
 constraint "PK_Ofertas" primary key 
(
	"IdOferta" ASC
)
)
;
;

create table if not exists public.Paises(
	"IdPais" integer generated by default as identity NOT NULL,
	"Nombre" varchar(80) NOT NULL,
	"ISO_1" varchar(3) NOT NULL,
	"ISO_2" varchar(3) NOT NULL,
	"ISO_3" varchar(3) NOT NULL,
	"RegID" uuid default gen_random_uuid() NOT NULL,
 constraint "PAIS_PK" primary key 
(
	"IdPais" ASC
),
 constraint "UQ__Pais__FC850A7A15702A09" unique 
(
	"IdPais" ASC
)
)
;
;

create table if not exists public.Perfiles(
	"IdPerfil" integer generated by default as identity NOT NULL,
	"Nombre" char(256) NOT NULL,
	"Roles" text NOT NULL,
 constraint "PK_Perfiles" primary key 
(
	"IdPerfil" ASC
)
)
;
;

create table if not exists public.Porcentajes(
	"IdPorcentaje" integer generated by default as identity NOT NULL,
	"IdEmpresa" integer NOT NULL,
	"Year" integer NOT NULL,
	"PorcientoFinanciable" numeric(6,4) NOT NULL,
	"TasaMinima" numeric(6,4) NOT NULL,
	"CuotaMinima" integer NOT NULL,
	"CuotaMaxima" integer NOT NULL,
	"RegID" uuid default gen_random_uuid() NOT NULL,
 constraint "PK_IdPorcentaje" primary key 
(
	"IdPorcentaje" ASC
)
)
;
;

create table if not exists public.PrestamoClases(
	"IdPrestamoClase" integer NOT NULL,
	"Nombre" varchar(50) NOT NULL,
	"Abr" varchar(10) NOT NULL,
	"RegID" uuid default gen_random_uuid() NOT NULL,
 constraint "PK_ClasesPrestamos" primary key 
(
	"IdPrestamoClase" ASC
)
)
;
;

create table if not exists public.PrestamoHistorias(
	"IdPrestamoHistoria" integer generated by default as identity NOT NULL,
	"IdPrestamo" integer NOT NULL,
	"IdUsuario" integer NOT NULL,
	"FechaCreacion" timestamptz default now() NOT NULL,
	"FechaContacto" timestamptz NOT NULL,
	"Nota" text NOT NULL,
	"Contactado" boolean NOT NULL,
	"Recordatorio" boolean NULL,
	"FechaRecordatorio" timestamptz NULL,
	"RegID" uuid default gen_random_uuid() NOT NULL,
 constraint "PK_PrestamoHistorias" primary key 
(
	"IdPrestamoHistoria" ASC
)
)
;
;

create table if not exists public.Prestamos(
	"IdPrestamo" integer generated by default as identity NOT NULL,
	"Referencia" varchar(32) NULL,
	"Codigo"  AS ("Prefijo"||CONVERT(text,"PrestamoNo",(0))) stored,
	"Prefijo" varchar(16) NOT NULL,
	"PrestamoNo" integer NOT NULL,
	"IdCartera" integer NOT NULL,
	"UsuarioId" integer NOT NULL,
	"IdCuenta" integer NOT NULL,
	"IdFiador" integer NOT NULL,
	"IdTipoPrestamo" integer NOT NULL,
	"IdClasePrestamo" integer NOT NULL,
	"Riesgo" integer NOT NULL,
	"FechaCreacion" timestamptz default now() NOT NULL,
	"FechaPrimerPago" timestamptz NOT NULL,
	"CapitalPrestado" numeric(18,2) NOT NULL,
	"Interes" numeric(9,6) NOT NULL,
	"InteresMora" numeric(9,6) NOT NULL,
	"FrecuenciaPago" integer NOT NULL,
	"Cuotas" integer NOT NULL,
	"DiasGraciaMora" integer NOT NULL,
	"TasaDescuento" numeric(9,6) NOT NULL,
	"DiasAnticipadoDescuento" integer NOT NULL,
	"IdEstado" integer NOT NULL,
	"GastoCierre" numeric(18,2) NOT NULL,
	"GastoSeguro" numeric(18,2) NOT NULL,
	"GastoSeguroEnCuotas" integer NOT NULL,
	"EnviarBuro" boolean NOT NULL,
	"MontoSan" numeric(18,2) NOT NULL,
	"EnLegal" boolean NOT NULL,
	"IdRepresentante" integer NOT NULL,
	"Ingresos" numeric(18,2) NOT NULL,
	"IngresosOtros" numeric(18,2) NOT NULL,
	"Gastos" numeric(18,2) NOT NULL,
	"Castigada" boolean NOT NULL,
	"NotasDepuracion" text NULL,
	"Moneda" integer NOT NULL,
	"NombreFiador" varchar(64) NULL,
	"CedulaFiador" varchar(20) NULL,
	"DireccionFiador" varchar(128) NULL,
	"TelefonoFiador" varchar(20) NULL,
	"ComoPagaraPrestamo" varchar(256) NULL,
	"RequisitoDeLaSolicitud" integer NOT NULL,
	"EnviarLegal" boolean NOT NULL,
	"PagarGastoSeguroDesde" integer NOT NULL,
	"MontoVenta" numeric(18,2) NULL,
	"FechaVenda" timestamptz NULL,
	"CapitalVenta" numeric(18,2) NULL,
	"BalanceVenta" numeric(18,2) NULL,
	"RegID" uuid default gen_random_uuid() NOT NULL,
	"GastoGps" numeric(18,2) NOT NULL,
	"GastoGpsEnCuotas" integer NOT NULL,
	"PagarGastoGpsDesde" integer NOT NULL,
	"Penalidad" numeric(5,4) NOT NULL,
	"MaxAbonoSobreCapital" numeric(5,4) NOT NULL,
	"AccesoAppMobile" boolean NOT NULL,
	"NumeroSEGM" varchar(64) NULL,
	"TipoComprobante" integer NULL,
 constraint "PK_Prestamos" primary key 
(
	"IdPrestamo" ASC
)
)
;
;

create table if not exists public.PrestamoTipos(
	"IdPrestamoTipo" integer NOT NULL,
	"Nombre" varchar(50) NOT NULL,
	"Descripcion" varchar(1024) NULL,
	"RegID" uuid default gen_random_uuid() NOT NULL,
 constraint "PK_TiposPrestamos" primary key 
(
	"IdPrestamoTipo" ASC
)
)
;
;

create table if not exists public.ProcesoLegalTipos(
	"IdProcesoLegalTipo" integer generated by default as identity NOT NULL,
	"Nombre" varchar(50) NOT NULL,
	"RegID" uuid default gen_random_uuid() NOT NULL,
 constraint "PK_ProcesoLegalTipos" primary key 
(
	"IdProcesoLegalTipo" ASC
)
)
;
;

create table if not exists public.ProcesosLegales(
	"IdProcesoLegal" integer generated by default as identity NOT NULL,
	"IdPrestamo" integer NOT NULL,
	"IdProcesoLegalTipo" integer NOT NULL,
	"FechaInicio" timestamptz NOT NULL,
	"FechaFinal" timestamptz NULL,
	"NombreEncargado" varchar(128) NOT NULL,
	"Costo" numeric(18,2) NOT NULL,
	"Cerrado" boolean NOT NULL,
	"Recibido" boolean NOT NULL,
	"Notas" varchar(1024) NULL,
	"RegID" uuid default gen_random_uuid() NOT NULL,
 constraint "PK_ProcesosLegales" primary key 
(
	"IdProcesoLegal" ASC
)
)
;
;

create table if not exists public.Proveedores(
	"IdProveedor" integer generated by default as identity NOT NULL,
	"IdEmpresa" integer NOT NULL,
	"Identificacion" varchar(32) NULL,
	"Nombre" varchar(64) NOT NULL,
	"Direccion" varchar(256) NOT NULL,
	"Telefono" varchar(20) NOT NULL,
	"TasaComision" numeric(6,4) NOT NULL,
	"FechaIngreso" timestamptz NOT NULL,
	"RegID" uuid default gen_random_uuid() NOT NULL,
 constraint "PK_Agentes" primary key 
(
	"IdProveedor" ASC
)
)
;
;

create table if not exists public.Provincias(
	"IdProvincia" integer generated by default as identity NOT NULL,
	"Nombre" varchar(80) NULL,
	"IdPais" integer NOT NULL,
	"RegID" uuid default gen_random_uuid() NOT NULL,
 constraint "PK_Provincia" primary key 
(
	"IdProvincia" ASC
)
)
;
;

create table if not exists public.PruebasSimulacion(
	"IdSimulacionFactura" integer generated by default as identity NOT NULL,
	"IdEmpresa" integer NOT NULL,
	"NCF" varchar(19) NOT NULL,
	"FechaVencimientoNCF" varchar(32) NULL,
	"Monto" numeric(18,2) NOT NULL,
	"Itbis" numeric(18,2) NOT NULL,
	"TipoItbis" integer NOT NULL,
	"TipoNcf" integer NOT NULL,
	"DescripcionItem" varchar(128) NOT NULL,
	"EstadoSimulacion" varchar(32) NULL,
	"EcfQR" varchar(256) NULL,
	"Error" text NULL,
	"Fecha" timestamptz NOT NULL,
	"RncComprador" varchar(19) NULL,
	"CodigoSeguridad" varchar(8) NULL,
	"FechaFirma" varchar(32) NULL,
	"NCFModificado" varchar(19) NULL,
 constraint "PK_PruebasSimulacion" primary key 
(
	"IdSimulacionFactura" ASC
)
)
;
;

create table if not exists public.RecibosEnDepositos(
	"IdDeposito" integer NOT NULL,
	"IdRecibo" integer NOT NULL,
 constraint "PK_RecibosEnDepositos" primary key 
(
	"IdDeposito" ASC,
	"IdRecibo" ASC
)
)
;
;

create table if not exists public.ReferenciaPersonalTipos(
	"IdTipoReferenciaPersonal" integer generated by default as identity NOT NULL,
	"Nombre" varchar(50) NOT NULL,
	"RegID" uuid default gen_random_uuid() NOT NULL,
 constraint "PK_TiposRefenciasPersonales" primary key 
(
	"IdTipoReferenciaPersonal" ASC
)
)
;
;

create table if not exists public.ReferenciasPersonales(
	"IdReferenciaPersonal" integer generated by default as identity NOT NULL,
	"IdCuenta" integer NOT NULL,
	"IdTipoReferenciaPersonal" integer NOT NULL,
	"Nombre" varchar(128) NOT NULL,
	"Dirección" varchar(512) NULL,
	"Telefono" varchar(20) NULL,
	"RegID" uuid default gen_random_uuid() NOT NULL,
 constraint "PK_ReferenciasPersonales" primary key 
(
	"IdReferenciaPersonal" ASC
)
)
;
;

create table if not exists public.Representantes(
	"IdRepresentante" integer generated by default as identity NOT NULL,
	"IdProveedor" integer NOT NULL,
	"Identificacion" varchar(32) NULL,
	"Nombre" varchar(128) NOT NULL,
	"Direccion" varchar(256) NOT NULL,
	"Telefono" varchar(20) NOT NULL,
	"Activo" boolean NOT NULL,
	"RegID" uuid default gen_random_uuid() NOT NULL,
 constraint "PK_Representantes" primary key 
(
	"IdRepresentante" ASC
)
)
;
;

create table if not exists public.Restricciones(
	"IdRestriccion" integer generated by default as identity NOT NULL,
	"Nombre" varchar(64) NOT NULL,
	"RegID" uuid default gen_random_uuid() NOT NULL,
 constraint "PK_Restricciones" primary key 
(
	"IdRestriccion" ASC
)
)
;
;

create table if not exists public.Tasaciones(
	"IdTasacion" integer generated by default as identity NOT NULL,
	"IdModelo" integer NOT NULL,
	"Year" integer NOT NULL,
	"PrecioMercadoActual" numeric(9,2) NOT NULL,
	"RegID" uuid default gen_random_uuid() NOT NULL,
 constraint "PK_Tasaciones" primary key 
(
	"IdTasacion" ASC
)
)
;
;

create table if not exists public.Telefonos(
	"IdTelefono" integer generated by default as identity NOT NULL,
	"IdCuenta" integer NOT NULL,
	"Numero" varchar(48) NOT NULL,
	"TipoTelefono" char(1) NOT NULL,
	"RegID" uuid default gen_random_uuid() NOT NULL,
 constraint "PK_Telefonos" primary key 
(
	"IdTelefono" ASC
)
)
;
;

create table if not exists public.Traspasos(
	"IdTraspaso" integer generated by default as identity NOT NULL,
	"IdPrestamo" integer NOT NULL,
	"IdCuenta" integer NOT NULL,
	"Fecha" timestamptz NOT NULL,
	"Nota" text NOT NULL,
	"RegID" uuid default gen_random_uuid() NOT NULL,
 constraint "PK_Traspasos" primary key 
(
	"IdTraspaso" DESC
)
)
;
;

create table if not exists public.UsersInCarteras(
	"IdCartera" integer NOT NULL,
	"IdUsuario" integer NOT NULL,
 constraint "PK_UsersInCarteras" primary key 
(
	"IdCartera" ASC,
	"IdUsuario" ASC
)
)
;
;

create table if not exists public.Usuarios(
	"IdUsuario" integer generated by default as identity NOT NULL,
	"UserId" uuid NOT NULL,
	"Nombre" varchar(50) NULL,
	"Direccion" varchar(128) NULL,
	"Telefono" varchar(20) NULL,
	"IdCartera" integer NOT NULL,
	"CarteraPrincipal" varchar(64) NULL,
	"CajaAbierta" boolean NOT NULL,
	"HoraInicio" integer NOT NULL,
	"HoraFinal" integer NOT NULL,
	"DiasSemanas" varchar(14) NOT NULL,
	"HorarioSemanal" text NOT NULL,
	"FechaExpiracionClave" timestamptz NOT NULL,
	"RegID" uuid default gen_random_uuid() NOT NULL,
	"IdPerfil" integer NULL,
 constraint "PK_Usuarios" primary key 
(
	"IdUsuario" ASC
)
)
;
;

create table if not exists public.UsuariosEnGrupos(
	"IDUsuario" integer NOT NULL,
	"IDGrupo" integer NOT NULL,
 constraint "PK_UsuariosEnGrupos" primary key 
(
	"IDUsuario" ASC,
	"IDGrupo" ASC
)
)
;
;

create table if not exists public.Variables(
	"IdVariable" integer generated by default as identity NOT NULL,
	"Nombre" varchar(50) NOT NULL,
	"Valor" numeric(18,6) NOT NULL,
	"Tipo" integer NOT NULL,
	"Descripcion" varchar(1024) NULL,
	"RegID" uuid default gen_random_uuid() NOT NULL,
 constraint "PK_Variable" primary key 
(
	"IdVariable" ASC
)
)
;
;

create table if not exists public.VehiculoEstilos(
	"IdVehiculoEstilo" integer generated by default as identity NOT NULL,
	"Nombre" varchar(64) NOT NULL,
	"RegID" uuid default gen_random_uuid() NOT NULL,
 constraint "PK_VehiculoEstilos" primary key 
(
	"IdVehiculoEstilo" ASC
)
)
;
;

create table if not exists public.VehiculosEnPrestamos(
	"IdVehiculo" integer NOT NULL,
	"IdPrestamo" integer NOT NULL,
 constraint "PK_VehiculosEnPrestamos" primary key 
(
	"IdVehiculo" ASC,
	"IdPrestamo" ASC
)
)
;
;

create table if not exists public.VehiculoTipos(
	"IdVehiculoTipo" integer generated by default as identity NOT NULL,
	"Nombre" varchar(64) NOT NULL,
 constraint "PK_VehiculoTipos" primary key 
(
	"IdVehiculoTipo" ASC
)
)
;
;

create table if not exists dealer.Dealers(
	"IdDealer" integer generated by default as identity NOT NULL,
	"Nombre" varchar(50) NOT NULL,
	"IdEmpresa" integer NOT NULL,
	"RNC" varchar(20) NULL,
	"Presidente" varchar(64) NULL,
	"Direccion" varchar(128) NULL,
	"Telefono" varchar(20) NULL,
	"Tipo" integer NOT NULL,
	"IdUsuario" integer NOT NULL,
	"Horario" varchar(50) NULL,
	"Activo" boolean NOT NULL,
	"RegID" uuid default gen_random_uuid() NOT NULL,
 constraint "PK_Dealer" primary key 
(
	"IdDealer" ASC
)
)
;
;

create table if not exists dealer.DealersEnProcesosLegales(
	"IdDealer" integer NOT NULL,
	"IdProcesoLegal" integer NOT NULL,
	"Recibido" boolean NOT NULL,
	"Nota" varchar(1024) NULL,
	"RegID" uuid default gen_random_uuid() NOT NULL,
 constraint "PK_DealersEnProcesosLegales" primary key 
(
	"IdDealer" ASC,
	"IdProcesoLegal" ASC
)
)
;
;

create table if not exists dealer.Factura(
	"IdFactura" integer generated by default as identity NOT NULL,
	"IdDealer" integer NOT NULL,
	"Fecha" timestamptz NOT NULL,
	"NCF" varchar(19) NULL,
	"Vendedor" varchar(50) NULL,
	"Cliente" varchar(50) NULL,
	"Direccion" varchar(128) NULL,
	"Telefono" varchar(20) NULL,
	"Estatus" integer NOT NULL,
	"RegID" uuid default gen_random_uuid() NOT NULL,
 constraint "PK_Factura" primary key 
(
	"IdFactura" ASC
)
)
;
;

create table if not exists dealer.FacturasDetalles(
	"IdFacturaDetalle" integer generated by default as identity NOT NULL,
	"IdFactura" integer NOT NULL,
	"IdVehiculo" integer NOT NULL,
	"Descripcion" varchar(64) NOT NULL,
	"Monto" numeric(18,2) NOT NULL,
	"CostoTraspaso" numeric(18,2) NOT NULL,
	"Itbis" numeric(6,4) NOT NULL,
	"Descuento" numeric(18,2) NOT NULL,
	"Total" text generated always as ((("Monto"||"Monto"*"Itbis")||"CostoTraspaso")-"Descuento") stored,
	"RegID" uuid default gen_random_uuid() NOT NULL,
 constraint "PK_FacturasDetalles" primary key 
(
	"IdFacturaDetalle" ASC
)
)
;
;

create table if not exists dealer.FacturasMovimientos(
	"IdFacturaMovimiento" integer generated by default as identity NOT NULL,
	"IdFactura" integer NOT NULL,
	"TipoPago" integer NOT NULL,
	"Monto" numeric(18,0) NOT NULL,
	"Descripcion" varchar(50) NULL,
	"RegID" uuid default gen_random_uuid() NOT NULL,
 constraint "PK_FacturasMovimientos" primary key 
(
	"IdFacturaMovimiento" ASC
)
)
;
;

create table if not exists dealer.Liquidaciones(
	"IdLiquidacion" integer generated by default as identity NOT NULL,
	"IdDealer" integer NOT NULL,
	"IdBanco" integer NOT NULL,
	"TipoPago" integer NOT NULL,
	"Fecha" timestamptz NOT NULL,
	"Comision" numeric(18,2) NOT NULL,
	"NCF" varchar(19) NULL,
	"Referencia" varchar(50) NULL,
	"Cliente" varchar(50) NULL,
	"Cedula" varchar(13) NULL,
	"Direccion" varchar(128) NULL,
	"Telefono" varchar(20) NULL,
	"Estatus" integer NOT NULL,
	"RegID" uuid default gen_random_uuid() NOT NULL,
 constraint "PK_Liquidaciones" primary key 
(
	"IdLiquidacion" ASC
)
)
;
;

create table if not exists dealer.LiquidacionesDetalles(
	"IdLiquidacionDetalle" integer generated by default as identity NOT NULL,
	"IdLiquidacion" integer NOT NULL,
	"IdVehiculo" integer NOT NULL,
	"Descripcion" varchar(64) NOT NULL,
	"Monto" numeric(18,2) NOT NULL,
	"Gastos" numeric(18,2) NOT NULL,
	"Reembolso" text generated always as ("Monto"-"Gastos") stored,
	"RegID" uuid default gen_random_uuid() NOT NULL,
 constraint "PK_LiquidacionesDetalles" primary key 
(
	"IdLiquidacionDetalle" ASC
)
)
;
;

create table if not exists dealer.Vehiculos(
	"IdVehiculo" integer generated by default as identity NOT NULL,
	"IdModelo" integer NOT NULL,
	"Chasis" varchar(64) NOT NULL,
	"Placa" varchar(32) NULL,
	"Motor" varchar(32) NULL,
	"Matricula" varchar(32) NULL,
	"IdVehiculoTipo" integer NOT NULL,
	"Color" varchar(50) NULL,
	"Year" integer NULL,
	"FechaMatricula" timestamptz NULL,
	"PrecioVenta" numeric(18,2) NULL,
	"IdDealer" integer NOT NULL,
	"Fecha" timestamptz NOT NULL,
	"Referencia" varchar(18) NOT NULL,
	"PrecioMinimo" numeric(18,2) NOT NULL,
	"Costo" numeric(18,2) NOT NULL,
	"Estado" integer NOT NULL,
	"RegID" uuid default gen_random_uuid() NOT NULL,
 constraint "PK_Vehiculos" primary key 
(
	"IdVehiculo" ASC
)
)
;
;

create table if not exists dealer.VehiculosMovimientos(
	"IdVehiculoMovimiento" integer generated by default as identity NOT NULL,
	"IdVehiculo" integer NOT NULL,
	"TipoMovimiento" integer NOT NULL,
	"TipoMovimientoDescripcion" integer NOT NULL,
	"Descripcion" varchar(64) NULL,
	"Monto" numeric(18,2) NOT NULL,
	"Fecha" timestamptz NOT NULL,
	"RegID" uuid default gen_random_uuid() NOT NULL,
 constraint "PK_VehiculosMovimientos" primary key 
(
	"IdVehiculoMovimiento" ASC
)
)
;
;

create table if not exists tran.Amortizaciones(
	"IdAmortizacion" integer generated by default as identity NOT NULL,
	"IdPrestamo" integer NOT NULL,
	"OrdenPago" integer NOT NULL,
	"Vencimiento" timestamptz NOT NULL,
	"GastoCierre" numeric(18,2) NOT NULL,
	"Seguro" numeric(18,2) NOT NULL,
	"Interes" numeric(18,2) NOT NULL,
	"InteresMora" numeric(18,6) NOT NULL,
	"Capital" numeric(18,2) NOT NULL,
	"CapitalAjustado" numeric(18,2) NOT NULL,
	"GastoCierreAcumulado" numeric(18,2) NOT NULL,
	"SeguroAcumulado" numeric(18,2) NOT NULL,
	"InteresAcumulado" numeric(18,2) NOT NULL,
	"CapitalAcumulado" numeric(18,2) NOT NULL,
	"MoraAcumulado" numeric(18,2) NOT NULL,
	"DiasGraciaMora" integer NOT NULL,
	"DetenerMora" boolean NOT NULL,
	"Frecuencia" integer NOT NULL,
	"FechaFinMora" timestamptz NULL,
	"PagoFecha" timestamptz NULL,
	"RegID" uuid default gen_random_uuid() NOT NULL,
	"Gps" numeric(18,2) NOT NULL,
	"GpsAcumulado" numeric(18,2) NOT NULL,
	"MoraCalculada" numeric(18,2) NULL,
	"DescuentoMora" numeric(18,2) NOT NULL,
	"SeguroEnMora" numeric(18,2) NOT NULL,
	"Mora" text generated always as (case when "DetenerMora"=(1) then (0) else case when ((("Capital"||"Interes")||"GastoCierre")||"SeguroEnMora")*"InteresMora"=(0) then (0) else round((((("Capital"||"Interes")||"GastoCierre")||"SeguroEnMora")*"InteresMora")/(5),(0))*(5) end*case "Frecuencia" when (1) then case when datediff(day,"Vencimiento",coalesce("FechaFinMora",now()))<="DiasGraciaMora" then (0) else (datediff(month,"Vencimiento",coalesce("FechaFinMora",now()))||(1))||case when (datepart(day,coalesce("FechaFinMora",now()))-datepart(day,"Vencimiento"))>=(0) then (0) else (-1) end end when (2) then case when datediff(day,"Vencimiento",coalesce("FechaFinMora",now()))<=((14)||"DiasGraciaMora") then (0) else (datediff(month,"Vencimiento",coalesce("FechaFinMora",now()))||(1))||case when (datepart(day,coalesce("FechaFinMora",now()))-datepart(day,"Vencimiento"))>=(0) then (0) else (-1) end end when (3) then case when datediff(day,"Vencimiento",coalesce("FechaFinMora",now()))<=((7)||"DiasGraciaMora") then (0) else (1) end when (4) then case when datediff(day,"Vencimiento",coalesce("FechaFinMora",now()))<="DiasGraciaMora" then (0) else (1) end  end end-"DescuentoMora"),
 constraint "PK_Amortizaciones" primary key 
(
	"IdAmortizacion" ASC
)
)
;
;

create table if not exists tran.Balances(
	"IdBalance" integer NOT NULL,
	"CargosCierre" numeric(18,2) NOT NULL,
	"CargosSeguro" numeric(18,2) NOT NULL,
	"CargosCapital" numeric(18,2) NOT NULL,
	"CargosInteres" numeric(18,2) NOT NULL,
	"CargosOtros" numeric(18,2) NOT NULL,
	"CargosLegal" numeric(18,2) NOT NULL,
	"CargosMora" numeric(18,2) NOT NULL,
	"PagosCierre" numeric(18,2) NOT NULL,
	"PagosSeguro" numeric(18,2) NOT NULL,
	"PagosCapital" numeric(18,2) NOT NULL,
	"PagosInteres" numeric(18,2) NOT NULL,
	"PagosOtros" numeric(18,2) NOT NULL,
	"PagosLegal" numeric(18,2) NOT NULL,
	"PagosMora" numeric(18,2) NOT NULL,
	"DescuentoCierre" numeric(18,2) NOT NULL,
	"DescuentoSeguro" numeric(18,2) NOT NULL,
	"DescuentoOtros" numeric(18,2) NOT NULL,
	"DescuentoLegal" numeric(18,2) NOT NULL,
	"DescuentoMora" numeric(18,2) NOT NULL,
	"DescuentoInteres" numeric(18,2) NOT NULL,
	"DescuentoCapital" numeric(18,2) NOT NULL,
	"CargosGps" numeric(18,2) NOT NULL,
	"PagosGps" numeric(18,2) NOT NULL,
	"DescuentoGps" numeric(18,2) NOT NULL,
 constraint "PK_Balances" primary key 
(
	"IdBalance" ASC
)
)
;
;

create table if not exists tran.BkAmortizaciones(
	"ID" bigint generated by default as identity NOT NULL,
	"RegIDRecibo" uuid NOT NULL,
	"IdAmortizacion" integer NOT NULL,
	"IdPrestamo" integer NOT NULL,
	"OrdenPago" integer NOT NULL,
	"Vencimiento" timestamptz NOT NULL,
	"GastoCierre" numeric(18,2) NOT NULL,
	"Seguro" numeric(18,2) NOT NULL,
	"Interes" numeric(18,2) NOT NULL,
	"InteresMora" numeric(18,6) NOT NULL,
	"CapitalAjustado" numeric(18,2) NOT NULL,
	"Capital" numeric(18,2) NOT NULL,
	"GastoCierreAcumulado" numeric(18,2) NOT NULL,
	"SeguroAcumulado" numeric(18,2) NOT NULL,
	"InteresAcumulado" numeric(18,2) NOT NULL,
	"CapitalAcumulado" numeric(18,2) NOT NULL,
	"MoraAcumulado" numeric(18,2) NOT NULL,
	"DiasGraciaMora" integer NOT NULL,
	"DetenerMora" boolean NOT NULL,
	"Frecuencia" integer NOT NULL,
	"FechaFinMora" timestamptz NULL,
	"PagoFecha" timestamptz NULL,
	"IdEstado" integer NOT NULL,
	"RegID" uuid default gen_random_uuid() NOT NULL,
	"Gps" numeric(18,2) NOT NULL,
	"GpsAcumulado" numeric(18,2) NOT NULL,
	"EnLegal" boolean NULL,
	"DescuentoMora" numeric(18,0) NOT NULL,
	"SeguroEnMora" numeric(18,2) NOT NULL,
 constraint "PK_BkAmortizaciones" primary key 
(
	"ID" ASC
)
)
;
;

create table if not exists tran.BkBalances(
	"ID" bigint generated by default as identity NOT NULL,
	"RegIDRecibo" uuid NOT NULL,
	"IdBalance" integer NOT NULL,
	"CargosCierre" numeric(18,2) NOT NULL,
	"CargosSeguro" numeric(18,2) NOT NULL,
	"CargosCapital" numeric(18,2) NOT NULL,
	"CargosInteres" numeric(18,2) NOT NULL,
	"CargosOtros" numeric(18,2) NOT NULL,
	"CargosLegal" numeric(18,2) NOT NULL,
	"CargosMora" numeric(18,2) NOT NULL,
	"PagosCierre" numeric(18,2) NOT NULL,
	"PagosSeguro" numeric(18,2) NOT NULL,
	"PagosCapital" numeric(18,2) NOT NULL,
	"PagosInteres" numeric(18,2) NOT NULL,
	"PagosOtros" numeric(18,2) NOT NULL,
	"PagosLegal" numeric(18,2) NOT NULL,
	"PagosMora" numeric(18,2) NOT NULL,
	"DescuentoCierre" numeric(18,2) NOT NULL,
	"DescuentoSeguro" numeric(18,2) NOT NULL,
	"DescuentoOtros" numeric(18,2) NOT NULL,
	"DescuentoLegal" numeric(18,2) NOT NULL,
	"DescuentoMora" numeric(18,2) NOT NULL,
	"DescuentoInteres" numeric(18,2) NOT NULL,
	"DescuentoCapital" numeric(18,2) NOT NULL,
	"CargosGps" numeric(18,2) NOT NULL,
	"PagosGps" numeric(18,2) NOT NULL,
	"DescuentoGps" numeric(18,2) NOT NULL,
 constraint "PK_BkBalances" primary key 
(
	"ID" ASC
)
)
;
;

create table if not exists tran.EstadosCuentas(
	"IdEstadoCuenta" integer generated by default as identity NOT NULL,
	"IdPrestamo" integer NOT NULL,
	"Corte" timestamptz NOT NULL,
	"Capital" numeric(18,2) NOT NULL,
	"Interes" numeric(18,2) NOT NULL,
	"Cierre" numeric(18,2) NOT NULL,
	"Seguro" numeric(18,2) NOT NULL,
	"Gps" numeric(18,2) NOT NULL,
	"Mora" numeric(18,2) NOT NULL,
	"Legal" numeric(18,2) NOT NULL,
	"Otros" numeric(18,2) NOT NULL,
	"CuotasVencidas" integer NOT NULL,
	"MontoVencido" numeric(18,2) NOT NULL,
	"Estado" integer NOT NULL,
	"EnLegal" boolean NOT NULL,
	"RegID" uuid default gen_random_uuid() NOT NULL,
 constraint "PK_EstadosCuentas" primary key 
(
	"IdEstadoCuenta" ASC
)
)
;
;

create table if not exists tran.Movimientos(
	"IdMovimiento" integer generated by default as identity NOT NULL,
	"IdPrestamo" integer NOT NULL,
	"Fecha" timestamptz NOT NULL,
	"Monto" numeric(18,2) NOT NULL,
	"Tipo" integer NOT NULL,
	"IdReciboMovimiento" integer NOT NULL,
	"Descripcion" text NULL,
	"CobrarEn" timestamptz NULL,
	"RegID" uuid default gen_random_uuid() NOT NULL,
	"FechaReg" timestamptz NOT NULL,
 constraint "PK_Movimientos" primary key 
(
	"IdMovimiento" ASC
)
)
;
;

create table if not exists tran.RecibosMovimientos(
	"IdReciboMovimiento" integer generated by default as identity NOT NULL,
	"IdCartera" integer NOT NULL,
	"Secuencia" integer NOT NULL,
	"Codigo" varchar(64) NULL,
	"IdUsuario" integer NOT NULL,
	"FechaRecibido" timestamptz NOT NULL,
	"Monto" numeric(18,2) NOT NULL,
	"IdTipoPago" integer NOT NULL,
	"IdBanco" integer NOT NULL,
	"Referencia" varchar(50) NULL,
	"FechaReferencia" timestamptz NULL,
	"Nota" text NULL,
	"Descripcion" text NULL,
	"NCF" varchar(19) NULL,
	"RegID" uuid default gen_random_uuid() NOT NULL,
	"FechaRecibidoSinHoras"  AS (CONVERT(timestamptz,CONVERT(date,"FechaRecibido"))) stored,
	"Anulado" boolean NOT NULL,
	"FechaReg" timestamptz NOT NULL,
 constraint "PK_RecibosMovimientos" primary key 
(
	"IdReciboMovimiento" ASC
)
)
;
;

create table if not exists tran.TiposMovimientos(
	"IdTipoMovimiento" integer NOT NULL,
	"Nombre" varchar(50) NOT NULL,
	"Signo" integer NOT NULL,
	"OrdenCobro" integer NOT NULL,
	"IncluirCobroCaja" boolean NOT NULL,
	"RegID" uuid default gen_random_uuid() NOT NULL,
 constraint "PK_TiposMovimientos" primary key 
(
	"IdTipoMovimiento" ASC
)
)
;

alter table almacen."Amortizaciones" alter column \"Gps\" set default 0;
;

alter table almacen."Amortizaciones" alter column \"GpsAcumulado\" set default 0;
;

alter table public."Alertas" alter column "RegID" set default gen_random_uuid();
;

alter table public."AlertasDetalles" alter column "RegID" set default gen_random_uuid();
;

alter table public."aspnet_Applications" alter column \"ApplicationId\" set default gen_random_uuid();
;

alter table public."aspnet_Membership" alter column \"PasswordFormat\" set default 0;
;

alter table public."aspnet_Paths" alter column \"PathId\" set default gen_random_uuid();
;

alter table public."aspnet_PersonalizationPerUser" alter column \"Id\" set default gen_random_uuid();
;

alter table public."aspnet_Roles" alter column \"RoleId\" set default gen_random_uuid();
;

alter table public."aspnet_Users" alter column \"UserId\" set default gen_random_uuid();
;

alter table public."aspnet_Users" alter column \"MobileAlias\" set default NULL;
;

alter table public."aspnet_Users" alter column \"IsAnonymous\" set default 0;
;

alter table public."Bancos" alter column "isNotLock" set default 1;
;

alter table public."Bancos" alter column "imgUrl" set default '~/App_Themes/Image/Abierto.png';
;

alter table public."Bancos" alter column "RegID" set default gen_random_uuid();
;

alter table public."Carteras" alter column "FechaCreacion" set default now();
;

alter table public."Carteras" alter column "CedulaPresidente" set default ' ';
;

alter table public."Carteras" alter column "EstadoCivilAbogado" set default 1;
;

alter table public."Carteras" alter column "CedulaAbogado" set default '''';
;

alter table public."Carteras" alter column "DireccionAbogado" set default ' ';
;

alter table public."Carteras" alter column "ContadorCuentas" set default 0;
;

alter table public."Carteras" alter column "ContadorPrestamos" set default 0;
;

alter table public."Carteras" alter column "ContadorRecibos" set default 0;
;

alter table public."Carteras" alter column "Banco" set default '''';
;

alter table public."Carteras" alter column "NoCuenta" set default ' ';
;

alter table public."Carteras" alter column "IdTipoRecibo" set default 1;
;

alter table public."Carteras" alter column "ProcesoLegalAutomatico" set default 0;
;

alter table public."Carteras" alter column "CostoBasicoLegal" set default 0;
;

alter table public."Carteras" alter column "InicioProcesoLegalCuotasVencidas" set default 0;
;

alter table public."Carteras" alter column "InicioProcesoLegalDias" set default 30;
;

alter table public."Carteras" alter column "Testigo1" set default '';
;

alter table public."Carteras" alter column "Testigo2" set default '';
;

alter table public."Carteras" alter column "RegID" set default gen_random_uuid();
;

alter table public."Carteras" alter column \"PorcientoPagoMinimo\" set default 0.50;
;

alter table public."Carteras" alter column \"Penalidad\" set default 0.05;
;

alter table public."Carteras" alter column \"MaxAbonoSobreCapital\" set default 0.5;
;

alter table public."Carteras" alter column \"MinAbonoSobreCapital\" set default 0.3;
;

alter table public."Carteras" alter column "Activo" set default 1;
;

alter table public."Categorias" alter column "RegID" set default gen_random_uuid();
;

alter table public."Cotizaciones" alter column "RegID" set default gen_random_uuid();
;

alter table public."Cuentas" alter column "EstaEnListaNegra" set default 0;
;

alter table public."Cuentas" alter column "AceptarCheque" set default 0;
;

alter table public."Cuentas" alter column "Bloqueado" set default 0;
;

alter table public."Cuentas" alter column "BloquearCobro" set default 0;
;

alter table public."Cuentas" alter column "Descontar" set default 0;
;

alter table public."Cuentas" alter column \"Ingresos\" set default 0;
;

alter table public."Cuentas" alter column \"TipoDocumento\" set default 1;
;

alter table public."Cuentas" alter column \"Ocupacion\" set default 0;
;

alter table public."Cuentas" alter column \"TipoRecidencia\" set default 0;
;

alter table public."Cuentas" alter column "RegID" set default gen_random_uuid();
;

alter table public."Depositos" alter column "MontoTransferencia" set default 0;
;

alter table public."Depositos" alter column "CantidadTransferencia" set default 0;
;

alter table public."Depositos" alter column "Contabilizado" set default 0;
;

alter table public."Depositos" alter column "RegID" set default gen_random_uuid();
;

alter table public."DesembolsoDetalles" alter column \"RegID\" set default gen_random_uuid();
;

alter table public."DocumentosFisicos" alter column "ContentType" set default 'image/jpeg';
;

alter table public."DocumentosFisicos" alter column \"Etiqueta\" set default 0;
;

alter table public."DocumentosFisicos" alter column \"RegID\" set default gen_random_uuid();
;

alter table public."ELMAH_Error" alter column "ErrorId" set default gen_random_uuid();
;

alter table public."Empresas" alter column \"RegID\" set default gen_random_uuid();
;

alter table public."Empresas" alter column \"Activo\" set default 1;
;

alter table public."Empresas" alter column \"Penalidad\" set default 0.05;
;

alter table public."Empresas" alter column \"MaxAbonoSobreCapital\" set default 0.5;
;

alter table public."Empresas" alter column \"MinAbonoSobreCapital\" set default 0.3;
;

alter table public."Empresas" alter column \"ApiKey\" set default gen_random_uuid();
;

alter table public."Empresas" alter column \"AutoAsignarNcf\" set default 0;
;

alter table public."Empresas" alter column \"CertificacionDgii\" set default 0;
;

alter table public."EmpresasDeServicios" alter column "IdMunicipio" set default 1;
;

alter table public."EmpresasDeServicios" alter column \"RegID\" set default gen_random_uuid();
;

alter table public."Garantias" alter column "IdModelo" set default 0;
;

alter table public."Garantias" alter column "IdAseguradora" set default 0;
;

alter table public."Garantias" alter column "IdVehiculoEstilo" set default 0;
;

alter table public."Garantias" alter column "IdVehiculoTipo" set default 0;
;

alter table public."Garantias" alter column "ValorGarantia" set default 0;
;

alter table public."Garantias" alter column "IdGPS" set default 0;
;

alter table public."Garantias" alter column "RegID" set default gen_random_uuid();
;

alter table public."Grupos" alter column \"RegID\" set default gen_random_uuid();
;

alter table public."GruposRoles" alter column \"RegID\" set default gen_random_uuid();
;

alter table public."ListasNegras" alter column \"RegID\" set default gen_random_uuid();
;

alter table public."Localizaciones" alter column \"RegID\" set default gen_random_uuid();
;

alter table public."Marcas" alter column \"RegID\" set default gen_random_uuid();
;

alter table public."Modelos" alter column \"RegID\" set default gen_random_uuid();
;

alter table public."Municipios" alter column \"RegID\" set default gen_random_uuid();
;

alter table public."NotasListasNegras" alter column \"RegID\" set default gen_random_uuid();
;

alter table public."Ofertas" alter column \"RegID\" set default gen_random_uuid();
;

alter table public."Paises" alter column \"RegID\" set default gen_random_uuid();
;

alter table public."Porcentajes" alter column \"RegID\" set default gen_random_uuid();
;

alter table public."PrestamoClases" alter column \"RegID\" set default gen_random_uuid();
;

alter table public."PrestamoHistorias" alter column "Contactado" set default 0;
;

alter table public."PrestamoHistorias" alter column \"RegID\" set default gen_random_uuid();
;

alter table public."Prestamos" alter column "Riesgo" set default 1;
;

alter table public."Prestamos" alter column "IdEstado" set default 1;
;

alter table public."Prestamos" alter column "GastoSeguroEnCuotas" set default 3;
;

alter table public."Prestamos" alter column "EnLegal" set default 0;
;

alter table public."Prestamos" alter column "IdRepresentante" set default 1;
;

alter table public."Prestamos" alter column "Ingresos" set default 0;
;

alter table public."Prestamos" alter column "IngresosOtros" set default 0;
;

alter table public."Prestamos" alter column "Gastos" set default 0;
;

alter table public."Prestamos" alter column "Castigada" set default 0;
;

alter table public."Prestamos" alter column "Moneda" set default 1;
;

alter table public."Prestamos" alter column "RequisitoDeLaSolicitud" set default 0;
;

alter table public."Prestamos" alter column "EnviarLegal" set default 1;
;

alter table public."Prestamos" alter column \"PagarGastoSeguroDesde\" set default 0;
;

alter table public."Prestamos" alter column \"RegID\" set default gen_random_uuid();
;

alter table public."Prestamos" alter column \"GastoGps\" set default 0;
;

alter table public."Prestamos" alter column \"GastoGpsEnCuotas\" set default 0;
;

alter table public."Prestamos" alter column \"PagarGastoGpsDesde\" set default 0;
;

alter table public."Prestamos" alter column \"Penalidad\" set default 0.05;
;

alter table public."Prestamos" alter column \"MaxAbonoSobreCapital\" set default 0.5;
;

alter table public."Prestamos" alter column \"AccesoAppMobile\" set default 0;
;

alter table public."PrestamoTipos" alter column \"RegID\" set default gen_random_uuid();
;

alter table public."ProcesoLegalTipos" alter column \"RegID\" set default gen_random_uuid();
;

alter table public."ProcesosLegales" alter column "Cerrado" set default 0;
;

alter table public."ProcesosLegales" alter column \"Recibido\" set default 0;
;

alter table public."ProcesosLegales" alter column \"RegID\" set default gen_random_uuid();
;

alter table public."Proveedores" alter column "RegID" set default gen_random_uuid();
;

alter table public."Provincias" alter column \"RegID\" set default gen_random_uuid();
;

alter table public."PruebasSimulacion" alter column \"Fecha\" set default now();
;

alter table public."ReferenciaPersonalTipos" alter column \"RegID\" set default gen_random_uuid();
;

alter table public."ReferenciasPersonales" alter column "IdTipoReferenciaPersonal" set default 1;
;

alter table public."ReferenciasPersonales" alter column \"RegID\" set default gen_random_uuid();
;

alter table public."Representantes" alter column "Activo" set default 1;
;

alter table public."Representantes" alter column "RegID" set default gen_random_uuid();
;

alter table public."Restricciones" alter column \"RegID\" set default gen_random_uuid();
;

alter table public."Tasaciones" alter column \"RegID\" set default gen_random_uuid();
;

alter table public."Telefonos" alter column \"RegID\" set default gen_random_uuid();
;

alter table public."Traspasos" alter column \"RegID\" set default gen_random_uuid();
;

alter table public."Usuarios" alter column "IdCartera" set default 0;
;

alter table public."Usuarios" alter column "HoraInicio" set default 0;
;

alter table public."Usuarios" alter column "HoraFinal" set default 0;
;

alter table public."Usuarios" alter column "DiasSemanas" set default 0;
;

alter table public."Usuarios" alter column "HorarioSemanal" set default '""';
;

alter table public."Usuarios" alter column "FechaExpiracionClave" set default now();
;

alter table public."Usuarios" alter column "RegID" set default gen_random_uuid();
;

alter table public."Variables" alter column "Tipo" set default 2;
;

alter table public."Variables" alter column \"RegID\" set default gen_random_uuid();
;

alter table public."VehiculoEstilos" alter column \"RegID\" set default gen_random_uuid();
;

alter table dealer."Dealers" alter column \"Tipo\" set default 1;
;

alter table dealer."Dealers" alter column \"IdUsuario\" set default 0;
;

alter table dealer."Dealers" alter column \"Activo\" set default 1;
;

alter table dealer."Dealers" alter column \"RegID\" set default gen_random_uuid();
;

alter table dealer."DealersEnProcesosLegales" alter column \"RegID\" set default gen_random_uuid();
;

alter table dealer."Factura" alter column "Estatus" set default 1;
;

alter table dealer."Factura" alter column \"RegID\" set default gen_random_uuid();
;

alter table dealer."FacturasDetalles" alter column \"RegID\" set default gen_random_uuid();
;

alter table dealer."FacturasMovimientos" alter column \"RegID\" set default gen_random_uuid();
;

alter table dealer."Liquidaciones" alter column "Estatus" set default 1;
;

alter table dealer."Liquidaciones" alter column \"RegID\" set default gen_random_uuid();
;

alter table dealer."LiquidacionesDetalles" alter column \"RegID\" set default gen_random_uuid();
;

alter table dealer."Vehiculos" alter column \"Estado\" set default 2;
;

alter table dealer."Vehiculos" alter column \"RegID\" set default gen_random_uuid();
;

alter table dealer."VehiculosMovimientos" alter column \"RegID\" set default gen_random_uuid();
;

alter table tran."Amortizaciones" alter column "CapitalAjustado" set default 0;
;

alter table tran."Amortizaciones" alter column "GastoCierreAcumulado" set default 0;
;

alter table tran."Amortizaciones" alter column "SeguroAcumulado" set default 0;
;

alter table tran."Amortizaciones" alter column "InteresAcumulado" set default 0;
;

alter table tran."Amortizaciones" alter column "CapitalAcumulado" set default 0;
;

alter table tran."Amortizaciones" alter column "MoraAcumulado" set default 0;
;

alter table tran."Amortizaciones" alter column "DiasGraciaMora" set default 5;
;

alter table tran."Amortizaciones" alter column "DetenerMora" set default 0;
;

alter table tran."Amortizaciones" alter column "Frecuencia" set default 1;
;

alter table tran."Amortizaciones" alter column "RegID" set default gen_random_uuid();
;

alter table tran."Amortizaciones" alter column \"Gps\" set default 0;
;

alter table tran."Amortizaciones" alter column \"GpsAcumulado\" set default 0;
;

alter table tran."Amortizaciones" alter column \"MoraCalculada\" set default 0;
;

alter table tran."Amortizaciones" alter column \"DescuentoMora\" set default 0;
;

alter table tran."Amortizaciones" alter column \"SeguroEnMora\" set default 0;
;

alter table tran."Balances" alter column "CargosCierre" set default 0;
;

alter table tran."Balances" alter column "CargosSeguro" set default 0;
;

alter table tran."Balances" alter column "CargosCapital" set default 0;
;

alter table tran."Balances" alter column "CargosInteres" set default 0;
;

alter table tran."Balances" alter column "CargosOtros" set default 0;
;

alter table tran."Balances" alter column "CargosLegal" set default 0;
;

alter table tran."Balances" alter column "CargosMora" set default 0;
;

alter table tran."Balances" alter column "PagosCierre" set default 0;
;

alter table tran."Balances" alter column "PagosSeguro" set default 0;
;

alter table tran."Balances" alter column "PagosCapital" set default 0;
;

alter table tran."Balances" alter column "PagosInteres" set default 0;
;

alter table tran."Balances" alter column "PagosOtros" set default 0;
;

alter table tran."Balances" alter column "PagosLegal" set default 0;
;

alter table tran."Balances" alter column "PagosMora" set default 0;
;

alter table tran."Balances" alter column "DescuentoCierre" set default 0;
;

alter table tran."Balances" alter column "DescuentoSeguro" set default 0;
;

alter table tran."Balances" alter column "DescuentoOtros" set default 0;
;

alter table tran."Balances" alter column "DescuentoLegal" set default 0;
;

alter table tran."Balances" alter column "DescuentoMora" set default 0;
;

alter table tran."Balances" alter column "DescuentoInteres" set default 0;
;

alter table tran."Balances" alter column "DescuentoCapital" set default 0;
;

alter table tran."Balances" alter column \"CargosGps\" set default 0;
;

alter table tran."Balances" alter column \"PagosGps\" set default 0;
;

alter table tran."Balances" alter column \"DescuentoGps\" set default 0;
;

alter table tran."BkAmortizaciones" alter column \"Gps\" set default 0;
;

alter table tran."BkAmortizaciones" alter column \"GpsAcumulado\" set default 0;
;

alter table tran."BkAmortizaciones" alter column \"DescuentoMora\" set default 0;
;

alter table tran."BkAmortizaciones" alter column \"SeguroEnMora\" set default 0;
;

alter table tran."BkBalances" alter column \"CargosGps\" set default 0;
;

alter table tran."BkBalances" alter column \"PagosGps\" set default 0;
;

alter table tran."BkBalances" alter column \"DescuentoGps\" set default 0;
;

alter table tran."Movimientos" alter column \"RegID\" set default gen_random_uuid();
;

alter table tran."Movimientos" alter column \"FechaReg\" set default now();
;

alter table tran."RecibosMovimientos" alter column "RegID" set default gen_random_uuid();
;

alter table tran."RecibosMovimientos" alter column \"Anulado\" set default 0;
;

alter table tran."RecibosMovimientos" alter column \"FechaReg\" set default now();
;

alter table tran."TiposMovimientos" alter column \"RegID\" set default gen_random_uuid();
;

ALTER TABLE public."Alertas" ADD  constraint "FK_Alertas_Usuarios" FOREIGN KEY("IdUsuario")
REFERENCES public."Usuarios" ("IdUsuario")
;



ALTER TABLE public."AlertasDetalles" ADD  constraint "FK_AlertasDetalles_Alertas" FOREIGN KEY("IdAlerta")
REFERENCES public."Alertas" ("IdAlerta")
ON DELETE CASCADE
;



ALTER TABLE public."AlertasDetalles" ADD  constraint "FK_AlertasDetalles_Restricciones" FOREIGN KEY("IdRestriccion")
REFERENCES public."Restricciones" ("IdRestriccion")
;



ALTER TABLE public."aspnet_Membership"  WITH NOCHECK ADD FOREIGN KEY("ApplicationId")
REFERENCES public."aspnet_Applications" ("ApplicationId")
;

ALTER TABLE public."aspnet_Membership"  WITH NOCHECK ADD FOREIGN KEY("UserId")
REFERENCES public."aspnet_Users" ("UserId")
;

ALTER TABLE public."aspnet_Paths" ADD FOREIGN KEY("ApplicationId")
REFERENCES public."aspnet_Applications" ("ApplicationId")
;

ALTER TABLE public."aspnet_PersonalizationAllUsers" ADD FOREIGN KEY("PathId")
REFERENCES public."aspnet_Paths" ("PathId")
;

ALTER TABLE public."aspnet_PersonalizationPerUser" ADD FOREIGN KEY("PathId")
REFERENCES public."aspnet_Paths" ("PathId")
;

ALTER TABLE public."aspnet_PersonalizationPerUser" ADD FOREIGN KEY("UserId")
REFERENCES public."aspnet_Users" ("UserId")
;

ALTER TABLE public."aspnet_Profile"  WITH NOCHECK ADD FOREIGN KEY("UserId")
REFERENCES public."aspnet_Users" ("UserId")
;

ALTER TABLE public."aspnet_Roles"  WITH NOCHECK ADD FOREIGN KEY("ApplicationId")
REFERENCES public."aspnet_Applications" ("ApplicationId")
;

ALTER TABLE public."aspnet_Users"  WITH NOCHECK ADD FOREIGN KEY("ApplicationId")
REFERENCES public."aspnet_Applications" ("ApplicationId")
;

ALTER TABLE public."aspnet_UsersInRoles"  WITH NOCHECK ADD FOREIGN KEY("RoleId")
REFERENCES public."aspnet_Roles" ("RoleId")
;

ALTER TABLE public."aspnet_UsersInRoles"  WITH NOCHECK ADD FOREIGN KEY("UserId")
REFERENCES public."aspnet_Users" ("UserId")
;

ALTER TABLE public."Carteras"  WITH NOCHECK ADD  constraint "FK_Carteras_Empresas" FOREIGN KEY("IdEmpresa")
REFERENCES public."Empresas" ("IdEmpresa")
;



ALTER TABLE public."Cotizaciones"  WITH NOCHECK ADD  constraint "FK_Cotizaciones_Usuarios" FOREIGN KEY("IdUsuario")
REFERENCES public."Usuarios" ("IdUsuario")
;



ALTER TABLE public."Cuentas"  WITH NOCHECK ADD  constraint "FK_Cuentas_Carteras" FOREIGN KEY("IdCartera")
REFERENCES public."Carteras" ("IdCartera")
;



ALTER TABLE public."Cuentas"  WITH NOCHECK ADD  constraint "FK_Cuentas_Usuarios" FOREIGN KEY("UsuarioId")
REFERENCES public."Usuarios" ("IdUsuario")
;



ALTER TABLE public."Depositos"  WITH NOCHECK ADD  constraint "FK_Depositos_Carteras" FOREIGN KEY("IdCartera")
REFERENCES public."Carteras" ("IdCartera")
;



ALTER TABLE public."Depositos"  WITH NOCHECK ADD  constraint "FK_Depositos_Usuarios" FOREIGN KEY("IdUsuario")
REFERENCES public."Usuarios" ("IdUsuario")
;



ALTER TABLE public."DesembolsoDetalles"  WITH NOCHECK ADD  constraint "FK_DesembolsoDetalles_Prestamos" FOREIGN KEY("IdPrestamo")
REFERENCES public."Prestamos" ("IdPrestamo")
ON DELETE CASCADE
;



ALTER TABLE public."DocumentosFisicosEnGaratia"  WITH NOCHECK ADD  constraint "FK_DocumentosFisicosEnGaratia_DocumentosFisicos" FOREIGN KEY("IdDocumentoFisico")
REFERENCES public."DocumentosFisicos" ("IdDocumentoFisico")
ON DELETE CASCADE
;



ALTER TABLE public."DocumentosFisicosEnGaratia"  WITH NOCHECK ADD  constraint "FK_DocumentosFisicosEnGaratia_Garantias" FOREIGN KEY("IdGarantia")
REFERENCES public."Garantias" ("IdGarantia")
ON DELETE CASCADE
;



ALTER TABLE public."DocumentosFisicosEnListaNegra" ADD  constraint "FK_DocumentosFisicosEnListaNegra_DocumentosFisicos" FOREIGN KEY("IdDocumentoFisico")
REFERENCES public."DocumentosFisicos" ("IdDocumentoFisico")
ON DELETE CASCADE
;



ALTER TABLE public."DocumentosFisicosEnListaNegra" ADD  constraint "FK_DocumentosFisicosEnListaNegra_ListasNegras" FOREIGN KEY("IdListaNegra")
REFERENCES public."ListasNegras" ("IdListaNegra")
ON DELETE CASCADE
;



ALTER TABLE public."DocumentosFisicosEnPrestamo"  WITH NOCHECK ADD  constraint "FK_DocumentosFisicosEnPrestamo_DocumentosFisicos" FOREIGN KEY("IdDocumentoFisico")
REFERENCES public."DocumentosFisicos" ("IdDocumentoFisico")
ON DELETE CASCADE
;



ALTER TABLE public."DocumentosFisicosEnPrestamo"  WITH NOCHECK ADD  constraint "FK_DocumentosFisicosEnPrestamo_Prestamos" FOREIGN KEY("IdPrestamo")
REFERENCES public."Prestamos" ("IdPrestamo")
ON DELETE CASCADE
;



ALTER TABLE public."EmpresasDeServicios"  WITH NOCHECK ADD  constraint "FK_EmpresasDeServicios_Municipios" FOREIGN KEY("IdMunicipio")
REFERENCES public."Municipios" ("IdMunicipio")
;



ALTER TABLE public."EmpresaServiciosEnEmpresas"  WITH NOCHECK ADD  constraint "FK_EmpresaServiciosEnEmpresas_Empresas" FOREIGN KEY("IdEmpresa")
REFERENCES public."Empresas" ("IdEmpresa")
;



ALTER TABLE public."EmpresaServiciosEnEmpresas"  WITH NOCHECK ADD  constraint "FK_EmpresaServiciosEnEmpresas_EmpresasDeServicios" FOREIGN KEY("IdEmpresaDeServicio")
REFERENCES public."EmpresasDeServicios" ("IdEmpresaDeServicio")
;



ALTER TABLE public."Garantias"  WITH NOCHECK ADD  constraint "FK_Garantias_Aseguradora" FOREIGN KEY("IdAseguradora")
REFERENCES public."EmpresasDeServicios" ("IdEmpresaDeServicio")
;



ALTER TABLE public."Garantias"  WITH NOCHECK ADD  constraint "FK_Garantias_GPS" FOREIGN KEY("IdGPS")
REFERENCES public."EmpresasDeServicios" ("IdEmpresaDeServicio")
;



ALTER TABLE public."Garantias"  WITH NOCHECK ADD  constraint "FK_Garantias_Modelos" FOREIGN KEY("IdModelo")
REFERENCES public."Modelos" ("IdModelo")
;



ALTER TABLE public."Garantias"  WITH NOCHECK ADD  constraint "FK_Garantias_Prestamos" FOREIGN KEY("IdPrestamo")
REFERENCES public."Prestamos" ("IdPrestamo")
ON DELETE CASCADE
;



ALTER TABLE public."Garantias"  WITH NOCHECK ADD  constraint "FK_Garantias_VehiculoEstilo" FOREIGN KEY("IdVehiculoEstilo")
REFERENCES public."VehiculoEstilos" ("IdVehiculoEstilo")
;



ALTER TABLE public."Garantias"  WITH NOCHECK ADD  constraint "FK_Garantias_VehiculoTipos" FOREIGN KEY("IdVehiculoTipo")
REFERENCES public."VehiculoTipos" ("IdVehiculoTipo")
;



ALTER TABLE public."GruposRoles"  WITH NOCHECK ADD  constraint "FK_GruposRoles_Grupos" FOREIGN KEY("IDGrupo")
REFERENCES public."Grupos" ("IDGrupo")
;



ALTER TABLE public."ListasNegras"  WITH NOCHECK ADD  constraint "FK_ListasNegras_Usuarios" FOREIGN KEY("IdUsuario")
REFERENCES public."Usuarios" ("IdUsuario")
;



ALTER TABLE public."Localizaciones"  WITH NOCHECK ADD  constraint "FK_Localizaciones_Cuentas" FOREIGN KEY("IdCuenta")
REFERENCES public."Cuentas" ("IdCuenta")
ON DELETE CASCADE
;



ALTER TABLE public."Localizaciones"  WITH NOCHECK ADD  constraint "FK_Localizaciones_Municipios" FOREIGN KEY("IdMunicipio")
REFERENCES public."Municipios" ("IdMunicipio")
;



ALTER TABLE public."Modelos"  WITH NOCHECK ADD  constraint "FK_Modelos_Marcas" FOREIGN KEY("IdMarca")
REFERENCES public."Marcas" ("IdMarca")
;



ALTER TABLE public."Municipios"  WITH NOCHECK ADD  constraint "FK_Municipio_Provincia" FOREIGN KEY("IdProvincia")
REFERENCES public."Provincias" ("IdProvincia")
;



ALTER TABLE public."NCFAsignaciones" ADD  constraint "FK_NCFAsignaciones_Movimientos" FOREIGN KEY("IdMovimiento")
REFERENCES tran."Movimientos" ("IdMovimiento")
;



ALTER TABLE public."NCFAsignaciones" ADD  constraint "FK_NCFAsignaciones_NCFDetalles" FOREIGN KEY("IdDetalleNcf")
REFERENCES public."NCFDetalles" ("IdDetalleNcf")
;



ALTER TABLE public."NCFDetalles" ADD  constraint "FK_NCFDetalles_NCFRangos" FOREIGN KEY("IdRangoNcf")
REFERENCES public."NCFRangos" ("IdRangoNcf")
;



ALTER TABLE public."NotasListasNegras" ADD  constraint "FK_NotasListasNegras_ListasNegras" FOREIGN KEY("IdListaNegra")
REFERENCES public."ListasNegras" ("IdListaNegra")
ON DELETE CASCADE
;



ALTER TABLE public."NotasListasNegras" ADD  constraint "FK_NotasListasNegras_Usuarios" FOREIGN KEY("IdUsuario")
REFERENCES public."Usuarios" ("IdUsuario")
;



ALTER TABLE public."Ofertas" ADD  constraint "FK_Ofertas_Agentes" FOREIGN KEY("IdProveedor")
REFERENCES public."Proveedores" ("IdProveedor")
;



ALTER TABLE public."Porcentajes"  WITH NOCHECK ADD  constraint "FK_Porcentajes_Empresas" FOREIGN KEY("IdEmpresa")
REFERENCES public."Empresas" ("IdEmpresa")
;



ALTER TABLE public."PrestamoHistorias"  WITH NOCHECK ADD  constraint "FK_PrestamoHistorias_Prestamos" FOREIGN KEY("IdPrestamo")
REFERENCES public."Prestamos" ("IdPrestamo")
ON DELETE CASCADE
;



ALTER TABLE public."PrestamoHistorias"  WITH NOCHECK ADD  constraint "FK_PrestamoHistorias_Usuarios" FOREIGN KEY("IdUsuario")
REFERENCES public."Usuarios" ("IdUsuario")
;



ALTER TABLE public."Prestamos"  WITH NOCHECK ADD  constraint "FK_Prestamos_Carteras" FOREIGN KEY("IdCartera")
REFERENCES public."Carteras" ("IdCartera")
;



ALTER TABLE public."Prestamos"  WITH NOCHECK ADD  constraint "FK_Prestamos_CuantaFiador" FOREIGN KEY("IdFiador")
REFERENCES public."Cuentas" ("IdCuenta")
;



ALTER TABLE public."Prestamos"  WITH NOCHECK ADD  constraint "FK_Prestamos_Cuentas" FOREIGN KEY("IdCuenta")
REFERENCES public."Cuentas" ("IdCuenta")
;



ALTER TABLE public."Prestamos"  WITH NOCHECK ADD  constraint "FK_Prestamos_Representantes" FOREIGN KEY("IdRepresentante")
REFERENCES public."Representantes" ("IdRepresentante")
;



ALTER TABLE public."Prestamos"  WITH NOCHECK ADD  constraint "FK_Prestamos_Usuarios" FOREIGN KEY("UsuarioId")
REFERENCES public."Usuarios" ("IdUsuario")
;



ALTER TABLE public."ProcesosLegales"  WITH NOCHECK ADD  constraint "FK_ProcesosLegales_Prestamos" FOREIGN KEY("IdPrestamo")
REFERENCES public."Prestamos" ("IdPrestamo")
ON DELETE CASCADE
;



ALTER TABLE public."ProcesosLegales"  WITH NOCHECK ADD  constraint "FK_ProcesosLegales_ProcesoLegalTipos" FOREIGN KEY("IdProcesoLegalTipo")
REFERENCES public."ProcesoLegalTipos" ("IdProcesoLegalTipo")
;



ALTER TABLE public."Proveedores"  WITH NOCHECK ADD  constraint "FK_Proveedores_Empresas" FOREIGN KEY("IdEmpresa")
REFERENCES public."Empresas" ("IdEmpresa")
;



ALTER TABLE public."Provincias"  WITH NOCHECK ADD  constraint "FK_Provincia_Pais" FOREIGN KEY("IdPais")
REFERENCES public."Paises" ("IdPais")
;



ALTER TABLE public."RecibosEnDepositos" ADD  constraint "FK_RecibosEnDepositos_Depositos" FOREIGN KEY("IdDeposito")
REFERENCES public."Depositos" ("IdDeposito")
;



ALTER TABLE public."RecibosEnDepositos" ADD  constraint "FK_RecibosEnDepositos_Recibos" FOREIGN KEY("IdRecibo")
REFERENCES tran."RecibosMovimientos" ("IdReciboMovimiento")
;



ALTER TABLE public."ReferenciasPersonales"  WITH NOCHECK ADD  constraint "FK_ReferenciasPersonales_Cuentas" FOREIGN KEY("IdCuenta")
REFERENCES public."Cuentas" ("IdCuenta")
ON DELETE CASCADE
;



ALTER TABLE public."ReferenciasPersonales"  WITH NOCHECK ADD  constraint "FK_ReferenciasPersonales_RefenciaPersonalTipos" FOREIGN KEY("IdTipoReferenciaPersonal")
REFERENCES public."ReferenciaPersonalTipos" ("IdTipoReferenciaPersonal")
;



ALTER TABLE public."Representantes"  WITH NOCHECK ADD  constraint "FK_Representantes_Proveedores" FOREIGN KEY("IdProveedor")
REFERENCES public."Proveedores" ("IdProveedor")
;



ALTER TABLE public."Tasaciones"  WITH NOCHECK ADD  constraint "FK_Tasaciones_Modelos" FOREIGN KEY("IdModelo")
REFERENCES public."Modelos" ("IdModelo")
;



ALTER TABLE public."Telefonos"  WITH NOCHECK ADD  constraint "FK_Telefonos_Cuentas" FOREIGN KEY("IdCuenta")
REFERENCES public."Cuentas" ("IdCuenta")
ON DELETE CASCADE
;



ALTER TABLE public."Traspasos"  WITH NOCHECK ADD  constraint "FK_Traspasos_Cuentas" FOREIGN KEY("IdCuenta")
REFERENCES public."Cuentas" ("IdCuenta")
;



ALTER TABLE public."Traspasos"  WITH NOCHECK ADD  constraint "FK_Traspasos_Prestamos" FOREIGN KEY("IdPrestamo")
REFERENCES public."Prestamos" ("IdPrestamo")
ON DELETE CASCADE
;



ALTER TABLE public."UsersInCarteras"  WITH NOCHECK ADD  constraint "FK_UsersInCarteras_Carteras" FOREIGN KEY("IdCartera")
REFERENCES public."Carteras" ("IdCartera")
;



ALTER TABLE public."UsersInCarteras"  WITH NOCHECK ADD  constraint "FK_UsersInCarteras_Usuarios" FOREIGN KEY("IdUsuario")
REFERENCES public."Usuarios" ("IdUsuario")
;



ALTER TABLE public."Usuarios"  WITH NOCHECK ADD  constraint "FK_Usuarios_aspnet_Users" FOREIGN KEY("UserId")
REFERENCES public."aspnet_Users" ("UserId")
;



ALTER TABLE public."Usuarios" ADD  constraint "FK_Usuarios_Perfiles" FOREIGN KEY("IdPerfil")
REFERENCES public."Perfiles" ("IdPerfil")
;



ALTER TABLE public."UsuariosEnGrupos"  WITH NOCHECK ADD  constraint "FK_UsuariosEnGrupos_Grupos" FOREIGN KEY("IDGrupo")
REFERENCES public."Grupos" ("IDGrupo")
;



ALTER TABLE public."UsuariosEnGrupos"  WITH NOCHECK ADD  constraint "FK_UsuariosEnGrupos_Usuarios" FOREIGN KEY("IDUsuario")
REFERENCES public."Usuarios" ("IdUsuario")
;



ALTER TABLE public."VehiculosEnPrestamos" ADD  constraint "FK_VehiculosEnPrestamos_Prestamos" FOREIGN KEY("IdPrestamo")
REFERENCES public."Prestamos" ("IdPrestamo")
ON DELETE CASCADE
;



ALTER TABLE public."VehiculosEnPrestamos" ADD  constraint "FK_VehiculosEnPrestamos_Vehiculos" FOREIGN KEY("IdVehiculo")
REFERENCES dealer."Vehiculos" ("IdVehiculo")
;



ALTER TABLE dealer."Dealers" ADD  constraint "FK_Dealer_Empresas" FOREIGN KEY("IdEmpresa")
REFERENCES public."Empresas" ("IdEmpresa")
;



ALTER TABLE dealer."Dealers" ADD  constraint "FK_Usuarios_Dealers" FOREIGN KEY("IdUsuario")
REFERENCES public."Usuarios" ("IdUsuario")
;



ALTER TABLE dealer."DealersEnProcesosLegales" ADD  constraint "FK_DealersEnProcesosLegales_dealer.Dealers" FOREIGN KEY("IdDealer")
REFERENCES dealer."Dealers" ("IdDealer")
;



ALTER TABLE dealer."DealersEnProcesosLegales" ADD  constraint "FK_DealersEnProcesosLegales_ProcesosLegales" FOREIGN KEY("IdProcesoLegal")
REFERENCES public."ProcesosLegales" ("IdProcesoLegal")
ON DELETE CASCADE
;



ALTER TABLE dealer."Factura" ADD  constraint "FK_Factura_dealer.Dealers" FOREIGN KEY("IdDealer")
REFERENCES dealer."Dealers" ("IdDealer")
;



ALTER TABLE dealer."FacturasDetalles" ADD  constraint "FK_FacturasDetalles_Factura" FOREIGN KEY("IdFactura")
REFERENCES dealer."Factura" ("IdFactura")
;



ALTER TABLE dealer."FacturasDetalles" ADD  constraint "FK_FacturasDetalles_Vehiculos" FOREIGN KEY("IdVehiculo")
REFERENCES dealer."Vehiculos" ("IdVehiculo")
;



ALTER TABLE dealer."FacturasMovimientos" ADD  constraint "FK_FacturasMovimientos_Factura" FOREIGN KEY("IdFactura")
REFERENCES dealer."Factura" ("IdFactura")
;



ALTER TABLE dealer."Liquidaciones" ADD  constraint "FK_Liquidaciones_Bancos" FOREIGN KEY("IdBanco")
REFERENCES public."Bancos" ("IdBanco")
;



ALTER TABLE dealer."Liquidaciones" ADD  constraint "FK_Liquidaciones_Dealers" FOREIGN KEY("IdDealer")
REFERENCES dealer."Dealers" ("IdDealer")
;



ALTER TABLE dealer."LiquidacionesDetalles" ADD  constraint "FK_LiquidacionesDetalles_Liquidaciones" FOREIGN KEY("IdLiquidacion")
REFERENCES dealer."Liquidaciones" ("IdLiquidacion")
;



ALTER TABLE dealer."LiquidacionesDetalles" ADD  constraint "FK_LiquidacionesDetalles_Vehiculos" FOREIGN KEY("IdVehiculo")
REFERENCES dealer."Vehiculos" ("IdVehiculo")
;



ALTER TABLE dealer."Vehiculos" ADD  constraint "FK_Vehiculos_Dealers" FOREIGN KEY("IdDealer")
REFERENCES dealer."Dealers" ("IdDealer")
;



ALTER TABLE dealer."Vehiculos" ADD  constraint "FK_Vehiculos_Modelos" FOREIGN KEY("IdModelo")
REFERENCES public."Modelos" ("IdModelo")
;



ALTER TABLE dealer."Vehiculos" ADD  constraint "FK_Vehiculos_VehiculoTipos" FOREIGN KEY("IdVehiculoTipo")
REFERENCES public."VehiculoTipos" ("IdVehiculoTipo")
;



ALTER TABLE dealer."VehiculosMovimientos" ADD  constraint "FK_VehiculosMovimientos_Vehiculos" FOREIGN KEY("IdVehiculo")
REFERENCES dealer."Vehiculos" ("IdVehiculo")
;



ALTER TABLE tran."Amortizaciones" ADD  constraint "FK_Amortizaciones_Prestamos" FOREIGN KEY("IdPrestamo")
REFERENCES public."Prestamos" ("IdPrestamo")
ON DELETE CASCADE
;



ALTER TABLE tran."Balances" ADD  constraint "FK_Balances_Prestamos" FOREIGN KEY("IdBalance")
REFERENCES public."Prestamos" ("IdPrestamo")
ON DELETE CASCADE
;



ALTER TABLE tran."EstadosCuentas" ADD  constraint "FK_EstadosCuentas_Prestamos" FOREIGN KEY("IdPrestamo")
REFERENCES public."Prestamos" ("IdPrestamo")
ON DELETE CASCADE
;



ALTER TABLE tran."Movimientos" ADD  constraint "FK_Movimientos_Prestamos" FOREIGN KEY("IdPrestamo")
REFERENCES public."Prestamos" ("IdPrestamo")
ON DELETE CASCADE
;



ALTER TABLE tran."Movimientos" ADD  constraint "FK_Movimientos_RecibosMovimientos" FOREIGN KEY("IdReciboMovimiento")
REFERENCES tran."RecibosMovimientos" ("IdReciboMovimiento")
;



ALTER TABLE tran."RecibosMovimientos" ADD  constraint "FK_RecibosMovimientos_Carteras" FOREIGN KEY("IdCartera")
REFERENCES public."Carteras" ("IdCartera")
;



ALTER TABLE tran."RecibosMovimientos" ADD  constraint "FK_RecibosMovimientos_Usuarios" FOREIGN KEY("IdUsuario")
REFERENCES public."Usuarios" ("IdUsuario")
;



ALTER TABLE public."Cuentas"  WITH NOCHECK ADD  constraint "CK_Cuentas_EstadoCivil" CHECK  (("EstadoCivil"='S' OR "EstadoCivil"='C' OR "EstadoCivil"='V' OR "EstadoCivil"='U' OR "EstadoCivil"='D' OR "EstadoCivil"='s' OR "EstadoCivil"='c' OR "EstadoCivil"='v' OR "EstadoCivil"='u' OR "EstadoCivil"='d'))
;



ALTER TABLE public."Cuentas"  WITH NOCHECK ADD  constraint "CK_Cuentas_Sexo" CHECK  (("Sexo"='M' OR "Sexo"='F' OR "Sexo"='m' OR "Sexo"='f'))
;


