-- Migración de tablas del esquema TRAN y más tablas importantes

-- Tablas del esquema tran (transaccionales)
CREATE TABLE IF NOT EXISTS tran.Amortizaciones(
	"IdAmortizacion" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"IdPrestamo" integer NOT NULL,
	"OrdenPago" integer NOT NULL,
	"Vencimiento" timestamptz NOT NULL,
	"GastoCierre" numeric(18,2) NOT NULL DEFAULT 0,
	"Seguro" numeric(18,2) NOT NULL DEFAULT 0,
	"Interes" numeric(18,2) NOT NULL DEFAULT 0,
	"InteresMora" numeric(18,6) NOT NULL DEFAULT 0,
	"Capital" numeric(18,2) NOT NULL DEFAULT 0,
	"CapitalAjustado" numeric(18,2) NOT NULL DEFAULT 0,
	"GastoCierreAcumulado" numeric(18,2) NOT NULL DEFAULT 0,
	"SeguroAcumulado" numeric(18,2) NOT NULL DEFAULT 0,
	"InteresAcumulado" numeric(18,2) NOT NULL DEFAULT 0,
	"CapitalAcumulado" numeric(18,2) NOT NULL DEFAULT 0,
	"MoraAcumulado" numeric(18,2) NOT NULL DEFAULT 0,
	"DiasGraciaMora" integer NOT NULL DEFAULT 0,
	"DetenerMora" boolean NOT NULL DEFAULT false,
	"Frecuencia" integer NOT NULL DEFAULT 30,
	"FechaFinMora" timestamptz NULL,
	"PagoFecha" timestamptz NULL,
	"RegID" uuid DEFAULT gen_random_uuid() NOT NULL,
	"Gps" numeric(18,2) NOT NULL DEFAULT 0,
	"GpsAcumulado" numeric(18,2) NOT NULL DEFAULT 0,
	"MoraCalculada" numeric(18,2) NULL DEFAULT 0,
	"DescuentoMora" numeric(18,2) NOT NULL DEFAULT 0,
	"SeguroEnMora" numeric(18,2) NOT NULL DEFAULT 0,
	CONSTRAINT "PK_TranAmortizaciones" PRIMARY KEY ("IdAmortizacion")
);

CREATE TABLE IF NOT EXISTS tran.Balances(
	"IdBalance" integer NOT NULL,
	"CargosCierre" numeric(18,2) NOT NULL DEFAULT 0,
	"CargosSeguro" numeric(18,2) NOT NULL DEFAULT 0,
	"CargosCapital" numeric(18,2) NOT NULL DEFAULT 0,
	"CargosInteres" numeric(18,2) NOT NULL DEFAULT 0,
	"CargosOtros" numeric(18,2) NOT NULL DEFAULT 0,
	"CargosLegal" numeric(18,2) NOT NULL DEFAULT 0,
	"CargosMora" numeric(18,2) NOT NULL DEFAULT 0,
	"PagosCierre" numeric(18,2) NOT NULL DEFAULT 0,
	"PagosSeguro" numeric(18,2) NOT NULL DEFAULT 0,
	"PagosCapital" numeric(18,2) NOT NULL DEFAULT 0,
	"PagosInteres" numeric(18,2) NOT NULL DEFAULT 0,
	"PagosOtros" numeric(18,2) NOT NULL DEFAULT 0,
	"PagosLegal" numeric(18,2) NOT NULL DEFAULT 0,
	"PagosMora" numeric(18,2) NOT NULL DEFAULT 0,
	"DescuentoCierre" numeric(18,2) NOT NULL DEFAULT 0,
	"DescuentoSeguro" numeric(18,2) NOT NULL DEFAULT 0,
	"DescuentoOtros" numeric(18,2) NOT NULL DEFAULT 0,
	"DescuentoLegal" numeric(18,2) NOT NULL DEFAULT 0,
	"DescuentoMora" numeric(18,2) NOT NULL DEFAULT 0,
	"DescuentoInteres" numeric(18,2) NOT NULL DEFAULT 0,
	"DescuentoCapital" numeric(18,2) NOT NULL DEFAULT 0,
	"CargosGps" numeric(18,2) NOT NULL DEFAULT 0,
	"PagosGps" numeric(18,2) NOT NULL DEFAULT 0,
	"DescuentoGps" numeric(18,2) NOT NULL DEFAULT 0,
	CONSTRAINT "PK_TranBalances" PRIMARY KEY ("IdBalance")
);

-- Tabla de Estados de Cuenta
CREATE TABLE IF NOT EXISTS tran.EstadosCuentas(
	"IdEstadoCuenta" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"IdPrestamo" integer NOT NULL,
	"Corte" timestamptz NOT NULL,
	"Capital" numeric(18,2) NOT NULL DEFAULT 0,
	"Interes" numeric(18,2) NOT NULL DEFAULT 0,
	"Cierre" numeric(18,2) NOT NULL DEFAULT 0,
	"Seguro" numeric(18,2) NOT NULL DEFAULT 0,
	"Gps" numeric(18,2) NOT NULL DEFAULT 0,
	"Mora" numeric(18,2) NOT NULL DEFAULT 0,
	"Legal" numeric(18,2) NOT NULL DEFAULT 0,
	"Total" numeric(18,2) NOT NULL DEFAULT 0,
	"RegID" uuid DEFAULT gen_random_uuid() NOT NULL,
	CONSTRAINT "PK_EstadosCuentas" PRIMARY KEY ("IdEstadoCuenta")
);

-- Tablas de Vehículos en Dealer
CREATE TABLE IF NOT EXISTS dealer.Vehiculos(
	"IdVehiculo" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"IdModelo" integer NOT NULL,
	"Chasis" varchar(64) NOT NULL,
	"Placa" varchar(32) NULL,
	"Motor" varchar(32) NULL,
	"Matricula" varchar(32) NULL,
	"IdVehiculoTipo" integer NOT NULL,
	"Color" varchar(50) NULL,
	"Year" integer NULL,
	"FechaMatricula" timestamptz NULL,
	"PrecioVenta" numeric(18,2) NULL DEFAULT 0,
	"IdDealer" integer NOT NULL,
	"Fecha" timestamptz NOT NULL DEFAULT now(),
	"Referencia" varchar(18) NOT NULL,
	"PrecioMinimo" numeric(18,2) NOT NULL DEFAULT 0,
	"Costo" numeric(18,2) NOT NULL DEFAULT 0,
	"Estado" integer NOT NULL DEFAULT 1,
	"RegID" uuid DEFAULT gen_random_uuid() NOT NULL,
	CONSTRAINT "PK_DealerVehiculos" PRIMARY KEY ("IdVehiculo")
);

CREATE TABLE IF NOT EXISTS dealer.VehiculosMovimientos(
	"IdVehiculoMovimiento" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"IdVehiculo" integer NOT NULL,
	"TipoMovimiento" integer NOT NULL DEFAULT 1,
	"TipoMovimientoDescripcion" integer NOT NULL DEFAULT 1,
	"Descripcion" varchar(64) NULL,
	"Monto" numeric(18,2) NOT NULL DEFAULT 0,
	"Fecha" timestamptz NOT NULL DEFAULT now(),
	"RegID" uuid DEFAULT gen_random_uuid() NOT NULL,
	CONSTRAINT "PK_VehiculosMovimientos" PRIMARY KEY ("IdVehiculoMovimiento")
);

-- Habilitar RLS en las nuevas tablas
ALTER TABLE tran.Amortizaciones ENABLE ROW LEVEL SECURITY;
ALTER TABLE tran.Balances ENABLE ROW LEVEL SECURITY;
ALTER TABLE tran.EstadosCuentas ENABLE ROW LEVEL SECURITY;
ALTER TABLE dealer.Vehiculos ENABLE ROW LEVEL SECURITY;
ALTER TABLE dealer.VehiculosMovimientos ENABLE ROW LEVEL SECURITY;

-- Políticas básicas
CREATE POLICY "TranAmortizaciones visibles para usuarios autenticados" ON tran.Amortizaciones FOR SELECT USING (auth.uid() IS NOT NULL);
CREATE POLICY "TranBalances visibles para usuarios autenticados" ON tran.Balances FOR SELECT USING (auth.uid() IS NOT NULL);
CREATE POLICY "EstadosCuentas visibles para usuarios autenticados" ON tran.EstadosCuentas FOR SELECT USING (auth.uid() IS NOT NULL);
CREATE POLICY "DealerVehiculos visibles para usuarios autenticados" ON dealer.Vehiculos FOR SELECT USING (auth.uid() IS NOT NULL);
CREATE POLICY "VehiculosMovimientos visibles para usuarios autenticados" ON dealer.VehiculosMovimientos FOR SELECT USING (auth.uid() IS NOT NULL);