-- Continuar con las tablas principales del sistema SIGP

-- Tabla de Empresas (prestamistas)
CREATE TABLE IF NOT EXISTS public.Empresas(
	"IdEmpresa" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"FechaCreacion" timestamptz DEFAULT now() NOT NULL,
	"RazonSocial" varchar(64) NOT NULL,
	"NombreComercial" varchar(64) NOT NULL,
	"RNC" varchar(20) NOT NULL,
	"Direccion" varchar(128) NOT NULL,
	"Telefono" varchar(256) NULL,
	"Presidente" varchar(64) NOT NULL,
	"CedulaPresidente" varchar(32) NOT NULL,
	"Abogado" varchar(64) NOT NULL,
	"EstadoCivilAbogado" integer NOT NULL DEFAULT 1,
	"CedulaAbogado" varchar(32) NOT NULL,
	"DireccionAbogado" varchar(128) NOT NULL,
	"Alguacil" varchar(64) NOT NULL,
	"Tasa" numeric(8,4) NOT NULL DEFAULT 0,
	"Mora" numeric(8,4) NOT NULL DEFAULT 0,
	"Cuotas" integer NOT NULL DEFAULT 12,
	"GastoCierre" numeric(8,4) NOT NULL DEFAULT 0,
	"UrlLogo" varchar(128) NOT NULL DEFAULT '',
	"Banco" varchar(64) NOT NULL DEFAULT '',
	"NoCuenta" varchar(20) NOT NULL DEFAULT '',
	"RegID" uuid DEFAULT gen_random_uuid() NOT NULL,
	"Activo" boolean NOT NULL DEFAULT true,
	"Penalidad" numeric(5,4) NOT NULL DEFAULT 0,
	"MaxAbonoSobreCapital" numeric(5,4) NOT NULL DEFAULT 1,
	"MinAbonoSobreCapital" numeric(5,4) NOT NULL DEFAULT 0,
	"ApiKey" uuid DEFAULT gen_random_uuid() NOT NULL,
	CONSTRAINT "PK_Empresas" PRIMARY KEY ("IdEmpresa")
);

-- Tabla de Estados para préstamos
CREATE TABLE IF NOT EXISTS public.Estados(
	"IdEstado" integer NOT NULL,
	"Nombre" varchar(50) NOT NULL,
	CONSTRAINT "PK_Estados" PRIMARY KEY ("IdEstado")
);

-- Insertar estados básicos
INSERT INTO public.Estados ("IdEstado", "Nombre") VALUES 
(1, 'Activo'),
(2, 'Pagado'), 
(3, 'Vencido'),
(4, 'En Cobro'),
(5, 'Cancelado')
ON CONFLICT DO NOTHING;

-- Tabla de Tipos de Préstamo
CREATE TABLE IF NOT EXISTS public.PrestamoTipos(
	"IdPrestamoTipo" integer NOT NULL,
	"Nombre" varchar(50) NOT NULL,
	"Descripcion" varchar(1024) NULL,
	"RegID" uuid DEFAULT gen_random_uuid() NOT NULL,
	CONSTRAINT "PK_PrestamoTipos" PRIMARY KEY ("IdPrestamoTipo")
);

-- Insertar tipos de préstamo básicos
INSERT INTO public.PrestamoTipos ("IdPrestamoTipo", "Nombre", "Descripcion") VALUES 
(1, 'Vehicular', 'Préstamos garantizados con vehículos'),
(2, 'Personal', 'Préstamos personales sin garantía específica'),
(3, 'Hipotecario', 'Préstamos garantizados con propiedades')
ON CONFLICT DO NOTHING;