-- Continuar migración - Esquema Dealer y más tablas

-- Tablas del esquema Dealer
CREATE TABLE IF NOT EXISTS dealer.Dealers(
	"IdDealer" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"Nombre" varchar(50) NOT NULL,
	"IdEmpresa" integer NOT NULL,
	"RNC" varchar(20) NULL,
	"Presidente" varchar(64) NULL,
	"Direccion" varchar(128) NULL,
	"Telefono" varchar(20) NULL,
	"Tipo" integer NOT NULL DEFAULT 1,
	"IdUsuario" integer NOT NULL,
	"Horario" varchar(50) NULL,
	"Activo" boolean NOT NULL DEFAULT true,
	"RegID" uuid DEFAULT gen_random_uuid() NOT NULL,
	CONSTRAINT "PK_Dealers" PRIMARY KEY ("IdDealer")
);

-- Tablas de relaciones de usuarios
CREATE TABLE IF NOT EXISTS public.UsersInCarteras(
	"IdCartera" integer NOT NULL,
	"IdUsuario" integer NOT NULL,
	CONSTRAINT "PK_UsersInCarteras" PRIMARY KEY ("IdCartera", "IdUsuario")
);

CREATE TABLE IF NOT EXISTS public.UsuariosEnGrupos(
	"IDUsuario" integer NOT NULL,
	"IDGrupo" integer NOT NULL,
	CONSTRAINT "PK_UsuariosEnGrupos" PRIMARY KEY ("IDUsuario", "IDGrupo")
);

-- Tabla de Procesos Legales
CREATE TABLE IF NOT EXISTS public.ProcesoLegalTipos(
	"IdProcesoLegalTipo" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"Nombre" varchar(50) NOT NULL,
	"RegID" uuid DEFAULT gen_random_uuid() NOT NULL,
	CONSTRAINT "PK_ProcesoLegalTipos" PRIMARY KEY ("IdProcesoLegalTipo")
);

CREATE TABLE IF NOT EXISTS public.ProcesosLegales(
	"IdProcesoLegal" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"IdPrestamo" integer NOT NULL,
	"IdProcesoLegalTipo" integer NOT NULL,
	"FechaInicio" timestamptz NOT NULL,
	"FechaFinal" timestamptz NULL,
	"NombreEncargado" varchar(128) NOT NULL,
	"Costo" numeric(18,2) NOT NULL DEFAULT 0,
	"Cerrado" boolean NOT NULL DEFAULT false,
	"Recibido" boolean NOT NULL DEFAULT false,
	"Notas" varchar(1024) NULL,
	"RegID" uuid DEFAULT gen_random_uuid() NOT NULL,
	CONSTRAINT "PK_ProcesosLegales" PRIMARY KEY ("IdProcesoLegal")
);

-- Insertar tipos de procesos legales básicos
INSERT INTO public.ProcesoLegalTipos ("Nombre") VALUES 
('Intimación'),
('Demanda'),
('Embargo'),
('Remate'),
('Recuperación'),
('Mediación')
ON CONFLICT DO NOTHING;

-- Tabla de Proveedores
CREATE TABLE IF NOT EXISTS public.Proveedores(
	"IdProveedor" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"IdEmpresa" integer NOT NULL,
	"Identificacion" varchar(32) NULL,
	"Nombre" varchar(64) NOT NULL,
	"Direccion" varchar(256) NOT NULL,
	"Telefono" varchar(20) NOT NULL,
	"TasaComision" numeric(6,4) NOT NULL DEFAULT 0,
	"FechaIngreso" timestamptz NOT NULL DEFAULT now(),
	"RegID" uuid DEFAULT gen_random_uuid() NOT NULL,
	CONSTRAINT "PK_Proveedores" PRIMARY KEY ("IdProveedor")
);

-- Tabla de Restricciones
CREATE TABLE IF NOT EXISTS public.Restricciones(
	"IdRestriccion" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"Nombre" varchar(64) NOT NULL,
	"RegID" uuid DEFAULT gen_random_uuid() NOT NULL,
	CONSTRAINT "PK_Restricciones" PRIMARY KEY ("IdRestriccion")
);

-- Tabla de Categorías
CREATE TABLE IF NOT EXISTS public.Categorias(
	"IdCategoria" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"Nombre" varchar(64) NOT NULL,
	"RegID" uuid DEFAULT gen_random_uuid() NOT NULL,
	CONSTRAINT "PK_Categorias" PRIMARY KEY ("IdCategoria")
);

-- Habilitar RLS
ALTER TABLE dealer.Dealers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.UsersInCarteras ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.UsuariosEnGrupos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ProcesoLegalTipos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ProcesosLegales ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.Proveedores ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.Restricciones ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.Categorias ENABLE ROW LEVEL SECURITY;

-- Políticas básicas
CREATE POLICY "Dealers visibles para usuarios autenticados" ON dealer.Dealers FOR SELECT USING (auth.uid() IS NOT NULL);
CREATE POLICY "UsersInCarteras visibles para usuarios autenticados" ON public.UsersInCarteras FOR SELECT USING (auth.uid() IS NOT NULL);
CREATE POLICY "UsuariosEnGrupos visibles para usuarios autenticados" ON public.UsuariosEnGrupos FOR SELECT USING (auth.uid() IS NOT NULL);
CREATE POLICY "ProcesoLegalTipos visibles para todos" ON public.ProcesoLegalTipos FOR SELECT USING (true);
CREATE POLICY "ProcesosLegales visibles para usuarios autenticados" ON public.ProcesosLegales FOR SELECT USING (auth.uid() IS NOT NULL);
CREATE POLICY "Proveedores visibles para usuarios autenticados" ON public.Proveedores FOR SELECT USING (auth.uid() IS NOT NULL);
CREATE POLICY "Restricciones visibles para usuarios autenticados" ON public.Restricciones FOR SELECT USING (auth.uid() IS NOT NULL);
CREATE POLICY "Categorias visibles para todos" ON public.Categorias FOR SELECT USING (true);