-- Continuar migración - Tablas de Referencias, Tasaciones y Vehículos

-- Tabla de Referencias Personales
CREATE TABLE IF NOT EXISTS public.ReferenciaPersonalTipos(
	"IdTipoReferenciaPersonal" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"Nombre" varchar(50) NOT NULL,
	"RegID" uuid DEFAULT gen_random_uuid() NOT NULL,
	CONSTRAINT "PK_ReferenciaPersonalTipos" PRIMARY KEY ("IdTipoReferenciaPersonal")
);

CREATE TABLE IF NOT EXISTS public.ReferenciasPersonales(
	"IdReferenciaPersonal" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"IdCuenta" integer NOT NULL,
	"IdTipoReferenciaPersonal" integer NOT NULL,
	"Nombre" varchar(128) NOT NULL,
	"Direccion" varchar(512) NULL,
	"Telefono" varchar(20) NULL,
	"RegID" uuid DEFAULT gen_random_uuid() NOT NULL,
	CONSTRAINT "PK_ReferenciasPersonales" PRIMARY KEY ("IdReferenciaPersonal")
);

-- Insertar tipos de referencias
INSERT INTO public.ReferenciaPersonalTipos ("Nombre") VALUES 
('Familiar'),
('Laboral'),
('Personal'),
('Comercial'),
('Vecinal')
ON CONFLICT DO NOTHING;

-- Tabla de Representantes
CREATE TABLE IF NOT EXISTS public.Representantes(
	"IdRepresentante" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"IdProveedor" integer NOT NULL,
	"Identificacion" varchar(32) NULL,
	"Nombre" varchar(128) NOT NULL,
	"Direccion" varchar(256) NOT NULL,
	"Telefono" varchar(20) NOT NULL,
	"Activo" boolean NOT NULL DEFAULT true,
	"RegID" uuid DEFAULT gen_random_uuid() NOT NULL,
	CONSTRAINT "PK_Representantes" PRIMARY KEY ("IdRepresentante")
);

-- Tabla de Tasaciones
CREATE TABLE IF NOT EXISTS public.Tasaciones(
	"IdTasacion" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"IdModelo" integer NOT NULL,
	"Year" integer NOT NULL,
	"PrecioMercadoActual" numeric(9,2) NOT NULL,
	"RegID" uuid DEFAULT gen_random_uuid() NOT NULL,
	CONSTRAINT "PK_Tasaciones" PRIMARY KEY ("IdTasacion")
);

-- Tabla de Teléfonos
CREATE TABLE IF NOT EXISTS public.Telefonos(
	"IdTelefono" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"IdCuenta" integer NOT NULL,
	"Numero" varchar(48) NOT NULL,
	"TipoTelefono" char(1) NOT NULL DEFAULT 'C',
	"RegID" uuid DEFAULT gen_random_uuid() NOT NULL,
	CONSTRAINT "PK_Telefonos" PRIMARY KEY ("IdTelefono")
);

-- Tabla de Traspasos
CREATE TABLE IF NOT EXISTS public.Traspasos(
	"IdTraspaso" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"IdPrestamo" integer NOT NULL,
	"IdCuenta" integer NOT NULL,
	"Fecha" timestamptz NOT NULL,
	"Nota" text NOT NULL,
	"RegID" uuid DEFAULT gen_random_uuid() NOT NULL,
	CONSTRAINT "PK_Traspasos" PRIMARY KEY ("IdTraspaso")
);

-- Tabla de Tipos de Vehículos
CREATE TABLE IF NOT EXISTS public.VehiculoTipos(
	"IdVehiculoTipo" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"Nombre" varchar(64) NOT NULL,
	CONSTRAINT "PK_VehiculoTipos" PRIMARY KEY ("IdVehiculoTipo")
);

-- Tabla de Estilos de Vehículos
CREATE TABLE IF NOT EXISTS public.VehiculoEstilos(
	"IdVehiculoEstilo" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"Nombre" varchar(64) NOT NULL,
	"RegID" uuid DEFAULT gen_random_uuid() NOT NULL,
	CONSTRAINT "PK_VehiculoEstilos" PRIMARY KEY ("IdVehiculoEstilo")
);

-- Insertar tipos y estilos de vehículos básicos
INSERT INTO public.VehiculoTipos ("Nombre") VALUES 
('Automóvil'),
('Motocicleta'),
('Camión'),
('SUV'),
('Jeepeta'),
('Camioneta'),
('Autobús')
ON CONFLICT DO NOTHING;

INSERT INTO public.VehiculoEstilos ("Nombre") VALUES 
('Sedán'),
('Hatchback'),
('Coupe'),
('Convertible'),
('Station Wagon'),
('Pickup'),
('Van')
ON CONFLICT DO NOTHING;

-- Tabla de Variables del Sistema
CREATE TABLE IF NOT EXISTS public.Variables(
	"IdVariable" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"Nombre" varchar(50) NOT NULL,
	"Valor" numeric(18,6) NOT NULL,
	"Tipo" integer NOT NULL DEFAULT 1,
	"Descripcion" varchar(1024) NULL,
	"RegID" uuid DEFAULT gen_random_uuid() NOT NULL,
	CONSTRAINT "PK_Variables" PRIMARY KEY ("IdVariable")
);

-- Habilitar RLS en las nuevas tablas
ALTER TABLE public.ReferenciaPersonalTipos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ReferenciasPersonales ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.Representantes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.Tasaciones ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.Telefonos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.Traspasos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.VehiculoTipos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.VehiculoEstilos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.Variables ENABLE ROW LEVEL SECURITY;