-- Completar migración - Tablas NCF, Documentos y más

-- Tablas de NCF (facturación fiscal RD)
CREATE TABLE IF NOT EXISTS public.NCFRangos(
	"IdRangoNcf" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"IdEmpresa" integer NOT NULL,
	"Tipo" integer NOT NULL DEFAULT 1,
	"Inicio" bigint NOT NULL,
	"Fin" bigint NOT NULL,
	"Vencimiento" timestamptz NULL,
	"FechaCreacion" timestamptz DEFAULT now() NOT NULL,
	"FechaModificacion" timestamptz NULL,
	"UsuarioCreacion" varchar(128) NOT NULL,
	"UsuarioModificacion" varchar(128) NULL,
	"RegID" uuid DEFAULT gen_random_uuid() NOT NULL,
	CONSTRAINT "PK_NCFRangos" PRIMARY KEY ("IdRangoNcf")
);

CREATE TABLE IF NOT EXISTS public.NCFDetalles(
	"IdDetalleNcf" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"IdRangoNcf" bigint NOT NULL,
	"RNC" varchar(20) NOT NULL,
	"Secuencia" bigint NOT NULL,
	"NCF" varchar(24) NOT NULL,
	"Disponible" boolean NOT NULL DEFAULT true,
	"Activo" boolean NOT NULL DEFAULT true,
	"FechaAsignacion" timestamptz NULL,
	"Monto" numeric(18,2) NULL DEFAULT 0,
	"Fecha" timestamptz NOT NULL DEFAULT now(),
	"RegID" uuid DEFAULT gen_random_uuid() NOT NULL,
	"EstadoDgii" integer NULL,
	"QrCode" text NULL,
	"AlertasDgii" text NULL,
	"SecuenciaUtilizadaDgii" boolean NULL DEFAULT false,
	"Errores" text NULL,
	"NCFModificado" varchar(24) NULL,
	"CodigoSeguridad" varchar(8) NULL,
	"FechaFirma" varchar(20) NULL,
	CONSTRAINT "PK_NCFDetalles" PRIMARY KEY ("IdDetalleNcf"),
	CONSTRAINT "IX_NCFDetalles" UNIQUE ("NCF", "RNC")
);

CREATE TABLE IF NOT EXISTS public.NCFAsignaciones(
	"IdDetalleNcf" bigint NOT NULL,
	"IdMovimiento" integer NOT NULL,
	CONSTRAINT "PK_NCFAsignaciones" PRIMARY KEY ("IdDetalleNcf", "IdMovimiento")
);

-- Tablas de Documentos Físicos
CREATE TABLE IF NOT EXISTS public.DocumentoFisicoTipos(
	"IdDocumentoFisicoTipo" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"Nombre" varchar(64) NOT NULL,
	"RegID" uuid DEFAULT gen_random_uuid() NOT NULL,
	CONSTRAINT "PK_DocumentoFisicoTipos" PRIMARY KEY ("IdDocumentoFisicoTipo")
);

CREATE TABLE IF NOT EXISTS public.DocumentosFisicos(
	"IdDocumentoFisico" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"IdDocumentoFisicoTipo" integer NOT NULL,
	"Identificacion" varchar(64) NOT NULL,
	"Nombre" varchar(128) NOT NULL,
	"Descripcion" varchar(256) NULL,
	"RegID" uuid DEFAULT gen_random_uuid() NOT NULL,
	CONSTRAINT "PK_DocumentosFisicos" PRIMARY KEY ("IdDocumentoFisico")
);

-- Insertar tipos de documentos básicos
INSERT INTO public.DocumentoFisicoTipos ("Nombre") VALUES 
('Cédula'),
('Licencia'),
('Pasaporte'),
('Certificado Trabajo'),
('Comprobante Ingresos'),
('Título Propiedad'),
('Matrícula Vehículo'),
('Póliza Seguro')
ON CONFLICT DO NOTHING;

-- Tablas de relación documentos
CREATE TABLE IF NOT EXISTS public.DocumentosFisicosEnPrestamo(
	"IdPrestamo" integer NOT NULL,
	"IdDocumentoFisico" integer NOT NULL,
	CONSTRAINT "PK_DocumentosFisicosEnPrestamo" PRIMARY KEY ("IdPrestamo", "IdDocumentoFisico")
);

CREATE TABLE IF NOT EXISTS public.DocumentosFisicosEnGaratia(
	"IdGarantia" integer NOT NULL,
	"IdDocumentoFisico" integer NOT NULL,
	CONSTRAINT "PK_DocumentosFisicosEnGaratia" PRIMARY KEY ("IdGarantia", "IdDocumentoFisico")
);

CREATE TABLE IF NOT EXISTS public.DocumentosFisicosEnListaNegra(
	"IdListaNegra" integer NOT NULL,
	"IdDocumentoFisico" integer NOT NULL,
	CONSTRAINT "PK_DocumentosFisicosEnListaNegra" PRIMARY KEY ("IdListaNegra", "IdDocumentoFisico")
);

-- Tabla de Recibos en Depósitos
CREATE TABLE IF NOT EXISTS public.RecibosEnDepositos(
	"IdDeposito" integer NOT NULL,
	"IdRecibo" integer NOT NULL,
	CONSTRAINT "PK_RecibosEnDepositos" PRIMARY KEY ("IdDeposito", "IdRecibo")
);

-- Habilitar RLS
ALTER TABLE public.NCFRangos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.NCFDetalles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.NCFAsignaciones ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.DocumentoFisicoTipos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.DocumentosFisicos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.DocumentosFisicosEnPrestamo ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.DocumentosFisicosEnGaratia ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.DocumentosFisicosEnListaNegra ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.RecibosEnDepositos ENABLE ROW LEVEL SECURITY;

-- Políticas básicas
CREATE POLICY "NCFRangos visibles para usuarios autenticados" ON public.NCFRangos FOR SELECT USING (auth.uid() IS NOT NULL);
CREATE POLICY "NCFDetalles visibles para usuarios autenticados" ON public.NCFDetalles FOR SELECT USING (auth.uid() IS NOT NULL);
CREATE POLICY "NCFAsignaciones visibles para usuarios autenticados" ON public.NCFAsignaciones FOR SELECT USING (auth.uid() IS NOT NULL);
CREATE POLICY "DocumentoFisicoTipos visibles para todos" ON public.DocumentoFisicoTipos FOR SELECT USING (true);
CREATE POLICY "DocumentosFisicos visibles para usuarios autenticados" ON public.DocumentosFisicos FOR SELECT USING (auth.uid() IS NOT NULL);
CREATE POLICY "DocumentosFisicosEnPrestamo visibles para usuarios autenticados" ON public.DocumentosFisicosEnPrestamo FOR SELECT USING (auth.uid() IS NOT NULL);
CREATE POLICY "DocumentosFisicosEnGaratia visibles para usuarios autenticados" ON public.DocumentosFisicosEnGaratia FOR SELECT USING (auth.uid() IS NOT NULL);
CREATE POLICY "DocumentosFisicosEnListaNegra visibles para usuarios autenticados" ON public.DocumentosFisicosEnListaNegra FOR SELECT USING (auth.uid() IS NOT NULL);
CREATE POLICY "RecibosEnDepositos visibles para usuarios autenticados" ON public.RecibosEnDepositos FOR SELECT USING (auth.uid() IS NOT NULL);