-- Continuar con más tablas del sistema SIGP

-- Tabla de Municipios y Provincias (geolocalización)
CREATE TABLE IF NOT EXISTS public.Paises(
	"IdPais" integer NOT NULL,
	"Nombre" varchar(50) NOT NULL,
	CONSTRAINT "PK_Paises" PRIMARY KEY ("IdPais")
);

INSERT INTO public.Paises ("IdPais", "Nombre") VALUES (1, 'República Dominicana') ON CONFLICT DO NOTHING;

CREATE TABLE IF NOT EXISTS public.Provincias(
	"IdProvincia" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"Nombre" varchar(80) NOT NULL,
	"IdPais" integer NOT NULL DEFAULT 1,
	"RegID" uuid DEFAULT gen_random_uuid() NOT NULL,
	CONSTRAINT "PK_Provincias" PRIMARY KEY ("IdProvincia")
);

CREATE TABLE IF NOT EXISTS public.Municipios(
	"IdMunicipio" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"Nombre" varchar(80) NOT NULL,
	"IdProvincia" integer NOT NULL,
	"RegID" uuid DEFAULT gen_random_uuid() NOT NULL,
	CONSTRAINT "PK_Municipios" PRIMARY KEY ("IdMunicipio")
);

-- Tabla de Marcas y Modelos de Vehículos
CREATE TABLE IF NOT EXISTS public.Marcas(
	"IdMarca" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"Nombre" varchar(50) NOT NULL,
	"RegID" uuid DEFAULT gen_random_uuid() NOT NULL,
	CONSTRAINT "PK_Marcas" PRIMARY KEY ("IdMarca")
);

CREATE TABLE IF NOT EXISTS public.Modelos(
	"IdModelo" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"IdMarca" integer NOT NULL,
	"Nombre" varchar(50) NOT NULL,
	"RegID" uuid DEFAULT gen_random_uuid() NOT NULL,
	CONSTRAINT "PK_Modelos" PRIMARY KEY ("IdModelo")
);

-- Insertar algunas marcas populares
INSERT INTO public.Marcas ("Nombre") VALUES 
('Toyota'),
('Nissan'),
('Honda'),
('Hyundai'),
('Kia'),
('Suzuki'),
('Mitsubishi'),
('Chevrolet'),
('Ford')
ON CONFLICT DO NOTHING;

-- Tabla de Aseguradoras
CREATE TABLE IF NOT EXISTS public.Aseguradoras(
	"IdAseguradora" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"Nombre" varchar(64) NOT NULL,
	"Telefono" varchar(20) NULL,
	"Direccion" varchar(256) NULL,
	"RegID" uuid DEFAULT gen_random_uuid() NOT NULL,
	CONSTRAINT "PK_Aseguradoras" PRIMARY KEY ("IdAseguradora")
);

-- Insertar aseguradoras principales de RD
INSERT INTO public.Aseguradoras ("Nombre", "Telefono") VALUES 
('Seguros Universales', '809-200-1515'),
('Seguros La Colonial', '809-381-5000'),
('Mapfre BHD Seguros', '809-381-0101'),
('Seguros Patria', '809-540-8000'),
('ARS Palic Salud', '809-563-7254')
ON CONFLICT DO NOTHING;

-- Habilitar RLS
ALTER TABLE public.Paises ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.Provincias ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.Municipios ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.Marcas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.Modelos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.Aseguradoras ENABLE ROW LEVEL SECURITY;

-- Políticas de solo lectura para catálogos
CREATE POLICY "Paises visibles para todos" ON public.Paises FOR SELECT USING (true);
CREATE POLICY "Provincias visibles para todos" ON public.Provincias FOR SELECT USING (true);
CREATE POLICY "Municipios visibles para todos" ON public.Municipios FOR SELECT USING (true);
CREATE POLICY "Marcas visibles para todos" ON public.Marcas FOR SELECT USING (true);
CREATE POLICY "Modelos visibles para todos" ON public.Modelos FOR SELECT USING (true);
CREATE POLICY "Aseguradoras visibles para usuarios autenticados" ON public.Aseguradoras FOR SELECT USING (auth.uid() IS NOT NULL);

-- Relaciones
ALTER TABLE public.Provincias ADD CONSTRAINT "FK_Provincias_Paises" 
  FOREIGN KEY ("IdPais") REFERENCES public.Paises ("IdPais");

ALTER TABLE public.Municipios ADD CONSTRAINT "FK_Municipios_Provincias" 
  FOREIGN KEY ("IdProvincia") REFERENCES public.Provincias ("IdProvincia");

ALTER TABLE public.Modelos ADD CONSTRAINT "FK_Modelos_Marcas" 
  FOREIGN KEY ("IdMarca") REFERENCES public.Marcas ("IdMarca");