-- Tabla de Amortizaciones (tabla de pagos principal)
CREATE TABLE IF NOT EXISTS public.Amortizaciones(
	"IdAmortizacion" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"IdPrestamo" integer NOT NULL,
	"OrdenPago" integer NOT NULL,
	"Vencimiento" timestamptz NOT NULL,
	"Capital" numeric(18,2) NOT NULL DEFAULT 0,
	"Interes" numeric(18,2) NOT NULL DEFAULT 0,
	"Mora" numeric(18,2) NOT NULL DEFAULT 0,
	"Seguro" numeric(18,2) NOT NULL DEFAULT 0,
	"GastoCierre" numeric(18,2) NOT NULL DEFAULT 0,
	"PagoFecha" timestamptz NULL,
	"EstaPagado" boolean NOT NULL DEFAULT false,
	"MontoPagado" numeric(18,2) NOT NULL DEFAULT 0,
	"RegID" uuid DEFAULT gen_random_uuid() NOT NULL,
	CONSTRAINT "PK_Amortizaciones" PRIMARY KEY ("IdAmortizacion")
);

-- Tabla de Recibos de Pagos
CREATE TABLE IF NOT EXISTS public.Recibos(
	"IdRecibo" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"IdPrestamo" integer NOT NULL,
	"NumeroRecibo" varchar(32) NOT NULL,
	"FechaPago" timestamptz DEFAULT now() NOT NULL,
	"MontoPagado" numeric(18,2) NOT NULL,
	"Concepto" varchar(256) NOT NULL,
	"RecibidoPor" varchar(64) NOT NULL,
	"Observaciones" text NULL,
	"RegID" uuid DEFAULT gen_random_uuid() NOT NULL,
	CONSTRAINT "PK_Recibos" PRIMARY KEY ("IdRecibo")
);

-- Tabla de Usuarios del Sistema
CREATE TABLE IF NOT EXISTS public.Usuarios(
	"IdUsuario" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"UserId" uuid REFERENCES auth.users(id) ON DELETE CASCADE,
	"IdEmpresa" integer NOT NULL,
	"NombreUsuario" varchar(32) NOT NULL,
	"Nombres" varchar(64) NOT NULL,
	"Apellidos" varchar(64) NOT NULL,
	"Email" varchar(64) NOT NULL,
	"Activo" boolean NOT NULL DEFAULT true,
	"FechaCreacion" timestamptz DEFAULT now() NOT NULL,
	"RegID" uuid DEFAULT gen_random_uuid() NOT NULL,
	CONSTRAINT "PK_Usuarios" PRIMARY KEY ("IdUsuario")
);

-- Habilitar RLS en las nuevas tablas
ALTER TABLE public.Amortizaciones ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.Recibos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.Usuarios ENABLE ROW LEVEL SECURITY;

-- Políticas de seguridad
CREATE POLICY "Amortizaciones visibles para usuarios autenticados" ON public.Amortizaciones
  FOR SELECT USING (auth.uid() IS NOT NULL);

CREATE POLICY "Usuarios pueden crear amortizaciones" ON public.Amortizaciones
  FOR INSERT WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "Usuarios pueden actualizar amortizaciones" ON public.Amortizaciones
  FOR UPDATE USING (auth.uid() IS NOT NULL);

CREATE POLICY "Recibos visibles para usuarios autenticados" ON public.Recibos
  FOR SELECT USING (auth.uid() IS NOT NULL);

CREATE POLICY "Usuarios pueden crear recibos" ON public.Recibos
  FOR INSERT WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "Usuarios pueden ver su propio perfil" ON public.Usuarios
  FOR SELECT USING (auth.uid() = "UserId");

CREATE POLICY "Usuarios pueden actualizar su propio perfil" ON public.Usuarios
  FOR UPDATE USING (auth.uid() = "UserId");

-- Crear relaciones (foreign keys)
ALTER TABLE public.Cuentas ADD CONSTRAINT "FK_Cuentas_Empresas" 
  FOREIGN KEY ("IdEmpresa") REFERENCES public.Empresas ("IdEmpresa");

ALTER TABLE public.Prestamos ADD CONSTRAINT "FK_Prestamos_Empresas" 
  FOREIGN KEY ("IdEmpresa") REFERENCES public.Empresas ("IdEmpresa");

ALTER TABLE public.Prestamos ADD CONSTRAINT "FK_Prestamos_Cuentas" 
  FOREIGN KEY ("IdCuenta") REFERENCES public.Cuentas ("IdCuenta");

ALTER TABLE public.Prestamos ADD CONSTRAINT "FK_Prestamos_Estados" 
  FOREIGN KEY ("IdEstado") REFERENCES public.Estados ("IdEstado");

ALTER TABLE public.Prestamos ADD CONSTRAINT "FK_Prestamos_Tipos" 
  FOREIGN KEY ("IdTipoPrestamo") REFERENCES public.PrestamoTipos ("IdPrestamoTipo");

ALTER TABLE public.Garantias ADD CONSTRAINT "FK_Garantias_Prestamos" 
  FOREIGN KEY ("IdPrestamo") REFERENCES public.Prestamos ("IdPrestamo") ON DELETE CASCADE;

ALTER TABLE public.Amortizaciones ADD CONSTRAINT "FK_Amortizaciones_Prestamos" 
  FOREIGN KEY ("IdPrestamo") REFERENCES public.Prestamos ("IdPrestamo") ON DELETE CASCADE;

ALTER TABLE public.Recibos ADD CONSTRAINT "FK_Recibos_Prestamos" 
  FOREIGN KEY ("IdPrestamo") REFERENCES public.Prestamos ("IdPrestamo") ON DELETE CASCADE;

ALTER TABLE public.Usuarios ADD CONSTRAINT "FK_Usuarios_Empresas" 
  FOREIGN KEY ("IdEmpresa") REFERENCES public.Empresas ("IdEmpresa");